import {
  TTR_ROUTE_POINTS,
  ttrRouteGroupId,
  type TtrCityDef,
  type TtrDestinationTicket,
  type TtrMapDefinition,
  type TtrRouteColor,
  type TtrRouteDef,
} from '../model.js';

const CITIES: readonly TtrCityDef[] = [
  { id: 'amsterdam', name: 'Amsterdam' },
  { id: 'angora', name: 'Angora' },
  { id: 'athina', name: 'Athina' },
  { id: 'barcelona', name: 'Barcelona' },
  { id: 'berlin', name: 'Berlin' },
  { id: 'brest', name: 'Brest' },
  { id: 'brindisi', name: 'Brindisi' },
  { id: 'bruxelles', name: 'Bruxelles' },
  { id: 'bucuresti', name: 'Bucuresti' },
  { id: 'budapest', name: 'Budapest' },
  { id: 'cadiz', name: 'Cadiz' },
  { id: 'constantinople', name: 'Constantinople' },
  { id: 'danzic', name: 'Danzic' },
  { id: 'dieppe', name: 'Dieppe' },
  { id: 'edinburgh', name: 'Edinburgh' },
  { id: 'erzurum', name: 'Erzurum' },
  { id: 'essen', name: 'Essen' },
  { id: 'frankfurt', name: 'Frankfurt' },
  { id: 'kharkov', name: 'Kharkov' },
  { id: 'kobenhavn', name: 'København' },
  { id: 'kyiv', name: 'Kyiv' },
  { id: 'lisboa', name: 'Lisboa' },
  { id: 'london', name: 'London' },
  { id: 'madrid', name: 'Madrid' },
  { id: 'marseille', name: 'Marseille' },
  { id: 'moskva', name: 'Moskva' },
  { id: 'munchen', name: 'München' },
  { id: 'palermo', name: 'Palermo' },
  { id: 'pamplona', name: 'Pamplona' },
  { id: 'paris', name: 'Paris' },
  { id: 'petrograd', name: 'Petrograd' },
  { id: 'riga', name: 'Riga' },
  { id: 'roma', name: 'Roma' },
  { id: 'rostov', name: 'Rostov' },
  { id: 'sarajevo', name: 'Sarajevo' },
  { id: 'sevastopol', name: 'Sevastopol' },
  { id: 'smolensk', name: 'Smolensk' },
  { id: 'smyrna', name: 'Smyrna' },
  { id: 'sochi', name: 'Sochi' },
  { id: 'sofia', name: 'Sofia' },
  { id: 'stockholm', name: 'Stockholm' },
  { id: 'venezia', name: 'Venezia' },
  { id: 'warszawa', name: 'Warszawa' },
  { id: 'wien', name: 'Wien' },
  { id: 'wilno', name: 'Wilno' },
  { id: 'zagrab', name: 'Zagrab' },
  { id: 'zurich', name: 'Zürich' },
];

/** [id, a, b, length, color, tunnel?, ferryLocomotives?] */
type RouteRow = readonly [
  id: string,
  a: string,
  b: string,
  length: number,
  color: TtrRouteColor,
  tunnel?: boolean,
  ferryLocomotives?: number,
];

const ROUTE_ROWS: readonly RouteRow[] = [
  ['ams-bru', 'bruxelles', 'amsterdam', 1, 'blue'],
  ['ams-ess', 'amsterdam', 'essen', 3, 'yellow'],
  ['ams-fra', 'amsterdam', 'frankfurt', 2, 'white'],
  ['ams-lon', 'london', 'amsterdam', 2, 'gray', false, 2],
  ['ang-con', 'angora', 'constantinople', 2, 'gray', true],
  ['ang-erz', 'angora', 'erzurum', 3, 'blue'],
  ['ang-smy', 'smyrna', 'angora', 3, 'orange', true],
  ['ath-bri', 'brindisi', 'athina', 4, 'gray', false, 1],
  ['ath-sar', 'athina', 'sarajevo', 4, 'green'],
  ['ath-smy', 'athina', 'smyrna', 2, 'gray', false, 1],
  ['ath-sof', 'athina', 'sofia', 3, 'purple'],
  ['bar-mad', 'madrid', 'barcelona', 2, 'yellow'],
  ['bar-mar', 'barcelona', 'marseille', 4, 'gray'],
  ['bar-pam', 'pamplona', 'barcelona', 2, 'gray', true],
  ['ber-dan', 'danzic', 'berlin', 4, 'gray'],
  ['ber-ess', 'essen', 'berlin', 2, 'blue'],
  ['ber-fra-1', 'frankfurt', 'berlin', 3, 'blue'],
  ['ber-fra-2', 'frankfurt', 'berlin', 3, 'red'],
  ['ber-war-1', 'warszawa', 'berlin', 4, 'purple'],
  ['ber-war-2', 'warszawa', 'berlin', 4, 'yellow'],
  ['ber-wie', 'wien', 'berlin', 3, 'green'],
  ['bre-die', 'dieppe', 'brest', 2, 'green'],
  ['bre-pam', 'brest', 'pamplona', 4, 'purple'],
  ['bre-par', 'brest', 'paris', 3, 'blue'],
  ['bri-pal', 'brindisi', 'palermo', 3, 'gray', false, 1],
  ['bri-rom', 'roma', 'brindisi', 2, 'white'],
  ['bru-die', 'dieppe', 'bruxelles', 2, 'green'],
  ['bru-fra', 'bruxelles', 'frankfurt', 2, 'blue'],
  ['bru-par-1', 'paris', 'bruxelles', 2, 'yellow'],
  ['bru-par-2', 'paris', 'bruxelles', 2, 'red'],
  ['buc-bud', 'bucuresti', 'budapest', 4, 'gray', true],
  ['buc-con', 'constantinople', 'bucuresti', 3, 'yellow'],
  ['buc-kyi', 'bucuresti', 'kyiv', 4, 'gray'],
  ['buc-sev', 'sevastopol', 'bucuresti', 4, 'white'],
  ['buc-sof', 'bucuresti', 'sofia', 2, 'gray', true],
  ['bud-kyi', 'kyiv', 'budapest', 6, 'gray', true],
  ['bud-sar', 'sarajevo', 'budapest', 3, 'purple'],
  ['bud-wie-1', 'wien', 'budapest', 1, 'red'],
  ['bud-wie-2', 'wien', 'budapest', 1, 'white'],
  ['bud-zag', 'zagrab', 'budapest', 2, 'orange'],
  ['cad-lis', 'lisboa', 'cadiz', 2, 'blue'],
  ['cad-mad', 'madrid', 'cadiz', 3, 'orange'],
  ['con-sev', 'constantinople', 'sevastopol', 4, 'gray', false, 2],
  ['con-smy', 'smyrna', 'constantinople', 2, 'gray', true],
  ['con-sof', 'constantinople', 'sofia', 3, 'blue'],
  ['dan-rig', 'riga', 'danzic', 3, 'blue'],
  ['dan-war', 'warszawa', 'danzic', 2, 'gray'],
  ['die-lon-1', 'london', 'dieppe', 2, 'gray', false, 1],
  ['die-lon-2', 'london', 'dieppe', 2, 'gray', false, 1],
  ['die-par', 'dieppe', 'paris', 1, 'purple'],
  ['edi-lon-1', 'edinburgh', 'london', 4, 'blue'],
  ['edi-lon-2', 'edinburgh', 'london', 4, 'orange'],
  ['erz-sev', 'erzurum', 'sevastopol', 4, 'gray', false, 2],
  ['erz-soc', 'erzurum', 'sochi', 3, 'red', true],
  ['ess-fra', 'frankfurt', 'essen', 2, 'green'],
  ['ess-kob-1', 'kobenhavn', 'essen', 3, 'gray', false, 1],
  ['ess-kob-2', 'kobenhavn', 'essen', 3, 'gray', false, 1],
  ['fra-mun', 'frankfurt', 'munchen', 2, 'purple'],
  ['fra-par-1', 'paris', 'frankfurt', 3, 'white'],
  ['fra-par-2', 'paris', 'frankfurt', 3, 'orange'],
  ['kha-kyi', 'kharkov', 'kyiv', 4, 'gray'],
  ['kha-mos', 'kharkov', 'moskva', 4, 'gray'],
  ['kha-ros', 'kharkov', 'rostov', 2, 'green'],
  ['kob-sto-1', 'stockholm', 'kobenhavn', 3, 'yellow'],
  ['kob-sto-2', 'stockholm', 'kobenhavn', 3, 'white'],
  ['kyi-smo', 'kyiv', 'smolensk', 3, 'red'],
  ['kyi-war', 'kyiv', 'warszawa', 4, 'gray'],
  ['kyi-wil', 'kyiv', 'wilno', 2, 'gray'],
  ['lis-mad', 'madrid', 'lisboa', 3, 'purple'],
  ['mad-pam-1', 'pamplona', 'madrid', 3, 'white', true],
  ['mad-pam-2', 'pamplona', 'madrid', 3, 'black', true],
  ['mar-pam', 'pamplona', 'marseille', 4, 'red'],
  ['mar-par', 'marseille', 'paris', 4, 'gray'],
  ['mar-rom', 'marseille', 'roma', 4, 'gray', true],
  ['mar-zur', 'marseille', 'zurich', 2, 'purple', true],
  ['mos-pet', 'moskva', 'petrograd', 4, 'white'],
  ['mos-smo', 'moskva', 'smolensk', 2, 'orange'],
  ['mun-ven', 'munchen', 'venezia', 2, 'blue', true],
  ['mun-wie', 'munchen', 'wien', 3, 'orange'],
  ['mun-zur', 'zurich', 'munchen', 2, 'yellow', true],
  ['pal-rom', 'roma', 'palermo', 4, 'gray', false, 1],
  ['pal-smy', 'palermo', 'smyrna', 6, 'gray', false, 2],
  ['pam-par-1', 'pamplona', 'paris', 4, 'blue'],
  ['pam-par-2', 'paris', 'pamplona', 4, 'green'],
  ['par-zur', 'paris', 'zurich', 3, 'gray', true],
  ['pet-rig', 'petrograd', 'riga', 4, 'gray'],
  ['pet-sto', 'petrograd', 'stockholm', 8, 'gray', true],
  ['pet-wil', 'wilno', 'petrograd', 4, 'blue'],
  ['rig-wil', 'wilno', 'riga', 4, 'green'],
  ['rom-ven', 'venezia', 'roma', 2, 'blue'],
  ['ros-sev', 'rostov', 'sevastopol', 4, 'gray'],
  ['ros-soc', 'sochi', 'rostov', 2, 'gray'],
  ['sar-sof', 'sarajevo', 'sofia', 2, 'gray', true],
  ['sar-zag', 'zagrab', 'sarajevo', 3, 'red'],
  ['sev-soc', 'sochi', 'sevastopol', 2, 'gray', false, 1],
  ['smo-wil', 'smolensk', 'wilno', 3, 'yellow'],
  ['ven-zag', 'venezia', 'zagrab', 2, 'gray'],
  ['ven-zur', 'zurich', 'venezia', 2, 'green', true],
  ['war-wie', 'warszawa', 'wien', 4, 'blue'],
  ['war-wil', 'wilno', 'warszawa', 3, 'red'],
  ['wie-zag', 'wien', 'zagrab', 2, 'green'],
];

const ROUTES: readonly TtrRouteDef[] = ROUTE_ROWS.map((row) => {
  const [id, a, b, length, color, tunnel, ferryLocomotives] = row;
  return {
    id,
    a,
    b,
    length,
    color,
    groupId: ttrRouteGroupId(a, b),
    ...(tunnel ? { tunnel: true } : {}),
    ...(ferryLocomotives ? { ferryLocomotives } : {}),
  };
});

const DESTINATION_TICKETS: readonly TtrDestinationTicket[] = [
  { id: 'ath-edi-t', a: 'edinburgh', b: 'athina', points: 21 },
  { id: 'cad-sto-t', a: 'cadiz', b: 'stockholm', points: 21 },
  { id: 'erz-kob-t', a: 'kobenhavn', b: 'erzurum', points: 21 },
  { id: 'bre-pet-t', a: 'brest', b: 'petrograd', points: 20 },
  { id: 'dan-lis-t', a: 'lisboa', b: 'danzic', points: 20 },
  { id: 'mos-pal-t', a: 'palermo', b: 'moskva', points: 20 },
  { id: 'fra-smo-t', a: 'frankfurt', b: 'smolensk', points: 13 },
  { id: 'ams-wil-t', a: 'amsterdam', b: 'wilno', points: 12 },
  { id: 'ber-mos-t', a: 'berlin', b: 'moskva', points: 12 },
  { id: 'ath-wil-t', a: 'athina', b: 'wilno', points: 11 },
  { id: 'ang-kha-t', a: 'angora', b: 'kharkov', points: 10 },
  { id: 'buc-rig-t', a: 'riga', b: 'bucuresti', points: 10 },
  { id: 'con-ven-t', a: 'venezia', b: 'constantinople', points: 10 },
  { id: 'ess-kyi-t', a: 'essen', b: 'kyiv', points: 10 },
  { id: 'lon-wie-t', a: 'london', b: 'wien', points: 10 },
  { id: 'sto-wie-t', a: 'stockholm', b: 'wien', points: 10 },
  { id: 'ber-rom-t', a: 'berlin', b: 'roma', points: 9 },
  { id: 'bru-dan-t', a: 'bruxelles', b: 'danzic', points: 9 },
  { id: 'bar-bru-t', a: 'barcelona', b: 'bruxelles', points: 8 },
  { id: 'bar-mun-t', a: 'barcelona', b: 'munchen', points: 8 },
  { id: 'ber-buc-t', a: 'berlin', b: 'bucuresti', points: 8 },
  { id: 'bre-ven-t', a: 'brest', b: 'venezia', points: 8 },
  { id: 'con-pal-t', a: 'palermo', b: 'constantinople', points: 8 },
  { id: 'die-mad-t', a: 'madrid', b: 'dieppe', points: 8 },
  { id: 'ess-mar-t', a: 'marseille', b: 'essen', points: 8 },
  { id: 'kyi-soc-t', a: 'kyiv', b: 'sochi', points: 8 },
  { id: 'mad-zur-t', a: 'madrid', b: 'zurich', points: 8 },
  { id: 'par-wie-t', a: 'paris', b: 'wien', points: 8 },
  { id: 'rom-smy-t', a: 'roma', b: 'smyrna', points: 8 },
  { id: 'ros-smo-t', a: 'smolensk', b: 'rostov', points: 8 },
  { id: 'sar-sev-t', a: 'sarajevo', b: 'sevastopol', points: 8 },
  { id: 'ams-pam-t', a: 'amsterdam', b: 'pamplona', points: 7 },
  { id: 'ber-lon-t', a: 'london', b: 'berlin', points: 7 },
  { id: 'bre-mar-t', a: 'brest', b: 'marseille', points: 7 },
  { id: 'edi-par-t', a: 'paris', b: 'edinburgh', points: 7 },
  { id: 'par-zag-t', a: 'paris', b: 'zagrab', points: 7 },
  { id: 'bri-zag-t', a: 'zagrab', b: 'brindisi', points: 6 },
  { id: 'bri-zur-t', a: 'zurich', b: 'brindisi', points: 6 },
  { id: 'bud-zur-t', a: 'zurich', b: 'budapest', points: 6 },
  { id: 'kyi-pet-t', a: 'kyiv', b: 'petrograd', points: 6 },
  { id: 'smo-war-t', a: 'warszawa', b: 'smolensk', points: 6 },
  { id: 'ang-ath-t', a: 'athina', b: 'angora', points: 5 },
  { id: 'bud-sof-t', a: 'budapest', b: 'sofia', points: 5 },
  { id: 'erz-ros-t', a: 'rostov', b: 'erzurum', points: 5 },
  { id: 'fra-kob-t', a: 'frankfurt', b: 'kobenhavn', points: 5 },
  { id: 'smy-sof-t', a: 'sofia', b: 'smyrna', points: 5 },
];

export const TTR_EUROPE_MAP: TtrMapDefinition = {
  id: 'europe',
  name: 'Europe',
  minPlayers: 2,
  maxPlayers: 5,
  trainsPerPlayer: 45,
  stationsPerPlayer: 3,
  unplacedStationBonus: 4,
  routePoints: TTR_ROUTE_POINTS,
  deck: { cardsPerColor: 12, locomotives: 14 },
  setup: {
    trainCards: 4,
    longTicketThreshold: 20,
    initialLongTickets: 1,
    initialRegularTickets: 3,
    minInitialKeep: 2,
    longTicketsMandatory: false,
    ticketDraw: 3,
    minTicketKeep: 1,
  },
  rules: {
    doubleRouteLockMaxPlayers: 3,
    oneRoutePerGroupPerPlayer: true,
    faceUpCount: 5,
    faceUpLocomotiveReset: 3,
    endgameTrainThreshold: 2,
    longestPathBonus: 10,
    mandalaBonus: false,
    tiebreak: 'europe',
  },
  cities: CITIES,
  routes: ROUTES,
  destinationTickets: DESTINATION_TICKETS,
};
