import {
  TTR_ROUTE_POINTS,
  ttrRouteGroupId,
  type TtrCityDef,
  type TtrDestinationTicket,
  type TtrMapDefinition,
  type TtrRouteColor,
  type TtrRouteDef,
} from '../model.js';

/**
 * Ticket to Ride — India (Map Collection 2).
 *
 * Rules deltas vs USA:
 * - 2–4 players; double routes lock at ≤3 (same policy as USA).
 * - Deal 4 destination tickets, keep ≥2; mid-game draw 3 keep ≥1 (no Long pile).
 * - Ferries (reuse Europe `ferryLocomotives`).
 * - Indian Express = longest continuous path (+10).
 * - Mandala / Grand Tour: ≥2 edge-disjoint paths on a completed ticket → tiered bonus.
 *
 * Route graph encoded from board art (`map-india_rma5ac`). Pink tracks → `purple`.
 * Ferry loco counts and a few lengths/colors are best-effort — correct via lab feedback.
 * Destination tickets: 58 (printed deck). City id/name `waltain` (printed as Waltair on some editions).
 */
const CITIES: readonly TtrCityDef[] = [
  { id: 'peshawar', name: 'Peshawar' },
  { id: 'lahore', name: 'Lahore' },
  { id: 'jacobabad', name: 'Jacobabad' },
  { id: 'bhatinda', name: 'Bhatinda' },
  { id: 'ambala', name: 'Ambala' },
  { id: 'rohri', name: 'Rohri' },
  { id: 'jodhpur', name: 'Jodhpur' },
  { id: 'delhi', name: 'Delhi' },
  { id: 'bareilly', name: 'Bareilly' },
  { id: 'lucknow', name: 'Lucknow' },
  { id: 'jarhat', name: 'Jarhat' },
  { id: 'karachi', name: 'Karachi' },
  { id: 'jaipur', name: 'Jaipur' },
  { id: 'agra', name: 'Agra' },
  { id: 'patna', name: 'Patna' },
  { id: 'dhubri', name: 'Dhubri' },
  { id: 'ahmadabad', name: 'Ahmadabad' },
  { id: 'ratiam', name: 'Ratiam' },
  { id: 'bhopal', name: 'Bhopal' },
  { id: 'katni', name: 'Katni' },
  { id: 'bilaspur', name: 'Bilaspur' },
  { id: 'calcutta', name: 'Calcutta' },
  { id: 'bombay', name: 'Bombay' },
  { id: 'khandwa', name: 'Khandwa' },
  { id: 'raipur', name: 'Raipur' },
  { id: 'chittagong', name: 'Chittagong' },
  { id: 'poona', name: 'Poona' },
  { id: 'manmad', name: 'Manmad' },
  { id: 'indur', name: 'Indur' },
  { id: 'wadi', name: 'Wadi' },
  { id: 'bezwada', name: 'Bezwada' },
  { id: 'waltain', name: 'Waltain' },
  { id: 'mormugao', name: 'Mormugao' },
  { id: 'guntakal', name: 'Guntakal' },
  { id: 'madras', name: 'Madras' },
  { id: 'mangalore', name: 'Mangalore' },
  { id: 'calicut', name: 'Calicut' },
  { id: 'erode', name: 'Erode' },
  { id: 'quilon', name: 'Quilon' },
];

/** [id, a, b, length, color, ferryLocomotives?] */
type RouteRow = readonly [
  id: string,
  a: string,
  b: string,
  length: number,
  color: TtrRouteColor,
  ferryLocomotives?: number,
];

const ROUTE_ROWS: readonly RouteRow[] = [
  // ── Northwest ──────────────────────────────────────────────
  ['pes-lah-1', 'peshawar', 'lahore', 1, 'purple'],
  ['pes-lah-2', 'peshawar', 'lahore', 1, 'green'],
  ['pes-jac-1', 'peshawar', 'jacobabad', 3, 'yellow'],
  ['pes-jac-2', 'peshawar', 'jacobabad', 3, 'orange'],
  ['lah-bha-1', 'lahore', 'bhatinda', 2, 'gray'],
  ['lah-bha-2', 'lahore', 'bhatinda', 2, 'gray'],
  ['lah-amb', 'lahore', 'ambala', 4, 'black'],
  ['jac-lah', 'jacobabad', 'lahore', 3, 'red'],
  ['jac-roh-1', 'jacobabad', 'rohri', 1, 'blue'],
  ['jac-roh-2', 'jacobabad', 'rohri', 1, 'green'],
  ['jac-kar', 'jacobabad', 'karachi', 4, 'white'],
  ['bha-amb-1', 'bhatinda', 'ambala', 2, 'white'],
  ['bha-amb-2', 'bhatinda', 'ambala', 2, 'yellow'],
  ['bha-roh', 'bhatinda', 'rohri', 2, 'purple'],
  ['bha-jod', 'bhatinda', 'jodhpur', 3, 'green'],
  ['bha-del', 'bhatinda', 'delhi', 3, 'blue'],
  ['amb-del-1', 'ambala', 'delhi', 2, 'gray'],
  ['amb-del-2', 'ambala', 'delhi', 2, 'gray'],
  ['amb-bar', 'ambala', 'bareilly', 2, 'orange'],
  ['roh-kar', 'rohri', 'karachi', 3, 'black'],
  ['jod-jai', 'jodhpur', 'jaipur', 2, 'red'],
  ['jod-kar', 'jodhpur', 'karachi', 3, 'orange'],
  ['del-bar', 'delhi', 'bareilly', 1, 'white'],
  ['del-luc', 'delhi', 'lucknow', 2, 'yellow'],
  ['del-agr', 'delhi', 'agra', 2, 'orange'],
  ['del-jai', 'delhi', 'jaipur', 2, 'purple'],
  ['bar-luc', 'bareilly', 'lucknow', 1, 'gray'],
  ['bar-pat', 'bareilly', 'patna', 4, 'green'],

  // ── Northeast ──────────────────────────────────────────────
  ['luc-kat-1', 'lucknow', 'katni', 1, 'black'],
  ['luc-kat-2', 'lucknow', 'katni', 1, 'blue'],
  ['luc-agr', 'lucknow', 'agra', 2, 'gray'],
  ['pat-dhu-1', 'patna', 'dhubri', 2, 'blue'],
  ['pat-dhu-2', 'patna', 'dhubri', 2, 'red'],
  ['pat-cal', 'patna', 'calcutta', 2, 'purple'],
  ['pat-kat-1', 'patna', 'katni', 2, 'gray'],
  ['pat-kat-2', 'patna', 'katni', 2, 'gray'],
  ['dhu-jar-1', 'dhubri', 'jarhat', 2, 'gray'],
  ['dhu-jar-2', 'dhubri', 'jarhat', 2, 'gray'],
  ['dhu-cal-1', 'dhubri', 'calcutta', 2, 'gray'],
  ['dhu-cal-2', 'dhubri', 'calcutta', 2, 'gray'],
  ['dhu-chi', 'dhubri', 'chittagong', 2, 'white'],
  ['jar-chi', 'jarhat', 'chittagong', 3, 'gray'],
  ['cal-chi-1', 'calcutta', 'chittagong', 2, 'gray', 1],
  ['cal-chi-2', 'calcutta', 'chittagong', 2, 'gray', 1],

  // ── West / center ──────────────────────────────────────────
  ['ahm-rat', 'ahmadabad', 'ratiam', 1, 'green'],
  ['ahm-bom', 'ahmadabad', 'bombay', 3, 'white'],
  ['ahm-kha', 'ahmadabad', 'khandwa', 2, 'yellow'],
  ['ahm-jod-1', 'ahmadabad', 'jodhpur', 3, 'purple'],
  ['ahm-jod-2', 'ahmadabad', 'jodhpur', 3, 'black'],
  ['jai-agr-1', 'jaipur', 'agra', 1, 'blue'],
  ['jai-agr-2', 'jaipur', 'agra', 1, 'white'],
  ['jai-rat-1', 'jaipur', 'ratiam', 1, 'orange'],
  ['jai-rat-2', 'jaipur', 'ratiam', 1, 'yellow'],
  ['agr-bho-1', 'agra', 'bhopal', 1, 'purple'],
  ['agr-bho-2', 'agra', 'bhopal', 1, 'red'],
  ['agr-kat', 'agra', 'katni', 2, 'green'],
  ['rat-bho', 'ratiam', 'bhopal', 2, 'black'],
  ['rat-kha', 'ratiam', 'khandwa', 2, 'gray'],
  ['bho-kha', 'bhopal', 'khandwa', 2, 'blue'],
  ['bho-bil-1', 'bhopal', 'bilaspur', 2, 'gray'],
  ['bho-bil-2', 'bhopal', 'bilaspur', 2, 'gray'],
  ['kat-bil-1', 'katni', 'bilaspur', 1, 'purple'],
  ['kat-bil-2', 'katni', 'bilaspur', 1, 'white'],
  ['bil-rai-1', 'bilaspur', 'raipur', 1, 'red'],
  ['bil-rai-2', 'bilaspur', 'raipur', 1, 'black'],
  ['bil-cal', 'bilaspur', 'calcutta', 4, 'yellow'],
  ['cal-wal', 'calcutta', 'waltain', 4, 'red'],
  ['cal-rai', 'calcutta', 'raipur', 4, 'blue'],

  // ── Central south ──────────────────────────────────────────
  ['bom-man', 'bombay', 'manmad', 1, 'black'],
  ['bom-poo', 'bombay', 'poona', 1, 'blue'],
  ['bom-mor', 'bombay', 'mormugao', 1, 'green'],
  ['kha-man', 'khandwa', 'manmad', 1, 'red'],
  ['kha-rai', 'khandwa', 'raipur', 4, 'orange'],
  ['man-poo', 'manmad', 'poona', 1, 'gray'],
  ['man-ind', 'manmad', 'indur', 3, 'purple'],
  ['rai-wal-1', 'raipur', 'waltain', 3, 'green'],
  ['rai-wal-2', 'raipur', 'waltain', 3, 'white'],
  ['ind-wad', 'indur', 'wadi', 2, 'gray'],
  ['ind-bez-1', 'indur', 'bezwada', 2, 'yellow'],
  ['ind-bez-2', 'indur', 'bezwada', 2, 'green'],
  ['poo-wad', 'poona', 'wadi', 1, 'orange'],
  ['poo-mor', 'poona', 'mormugao', 1, 'gray'],
  ['wad-gun-1', 'wadi', 'guntakal', 1, 'purple'],
  ['wad-gun-2', 'wadi', 'guntakal', 1, 'black'],
  ['wad-mor', 'wadi', 'mormugao', 2, 'gray'],
  ['bez-wal-1', 'bezwada', 'waltain', 2, 'black'],
  ['bez-wal-2', 'bezwada', 'waltain', 2, 'orange'],
  ['bez-gun', 'bezwada', 'guntakal', 2, 'blue'],
  ['bez-mad', 'bezwada', 'madras', 1, 'red'],
  ['wal-mad', 'waltain', 'madras', 3, 'yellow'],

  // ── Far south ──────────────────────────────────────────────
  ['mor-man', 'mormugao', 'mangalore', 2, 'black'],
  ['mor-gun', 'mormugao', 'guntakal', 2, 'red'],
  ['gun-mad', 'guntakal', 'madras', 2, 'white'],
  ['gun-man', 'guntakal', 'mangalore', 2, 'gray'],
  ['man-mad', 'mangalore', 'madras', 4, 'purple'],
  ['mad-ero-1', 'madras', 'erode', 2, 'green'],
  ['mad-ero-2', 'madras', 'erode', 2, 'orange'],
  ['man-cal-1', 'mangalore', 'calicut', 1, 'white'],
  ['man-cal-2', 'mangalore', 'calicut', 1, 'yellow'],
  ['cal-ero-1', 'calicut', 'erode', 3, 'red'],
  ['cal-ero-2', 'calicut', 'erode', 3, 'blue'],
  ['cal-qui-1', 'calicut', 'quilon', 2, 'gray', 1],
  ['cal-qui-2', 'calicut', 'quilon', 2, 'gray', 1],
  ['ero-qui', 'erode', 'quilon', 4, 'gray'],

  // ── Ferries ────────────────────────────────────────────────
  ['kar-bom-1', 'karachi', 'bombay', 6, 'gray', 2],
  ['kar-bom-2', 'karachi', 'bombay', 6, 'gray', 2],
  ['mad-cal-ferry', 'madras', 'calcutta', 8, 'gray', 2],
  ['bom-cal-ferry', 'bombay', 'calicut', 6, 'gray', 2],
];

const ROUTES: readonly TtrRouteDef[] = ROUTE_ROWS.map(
  ([id, a, b, length, color, ferryLocomotives]) => ({
    id,
    a,
    b,
    length,
    color,
    groupId: ttrRouteGroupId(a, b),
    ...(ferryLocomotives != null ? { ferryLocomotives } : {}),
  }),
);

/** 58 destination tickets from the India Map Collection deck. */
const DESTINATION_TICKETS: readonly TtrDestinationTicket[] = [
  { id: 'agra-jarhat', a: 'agra', b: 'jarhat', points: 8 },
  { id: 'ahm-calicut', a: 'ahmadabad', b: 'calicut', points: 7 },
  { id: 'amb-mormugao', a: 'ambala', b: 'mormugao', points: 10 },
  { id: 'amb-ratiam', a: 'ambala', b: 'ratiam', points: 5 },
  { id: 'amb-waltain', a: 'ambala', b: 'waltain', points: 9 },
  { id: 'bar-ahm', a: 'bareilly', b: 'ahmadabad', points: 5 },
  { id: 'bar-cal', a: 'bareilly', b: 'calcutta', points: 6 },
  { id: 'bar-guntakal', a: 'bareilly', b: 'guntakal', points: 10 },
  { id: 'bha-bezwada', a: 'bhatinda', b: 'bezwada', points: 13 },
  { id: 'bha-bilaspur', a: 'bhatinda', b: 'bilaspur', points: 7 },
  { id: 'bha-manmad', a: 'bhatinda', b: 'manmad', points: 9 },
  { id: 'bho-cal', a: 'bhopal', b: 'calcutta', points: 6 },
  { id: 'bho-mormugao', a: 'bhopal', b: 'mormugao', points: 5 },
  { id: 'bil-calicut', a: 'bilaspur', b: 'calicut', points: 10 },
  { id: 'bil-dhubri', a: 'bilaspur', b: 'dhubri', points: 5 },
  { id: 'bom-bezwada', a: 'bombay', b: 'bezwada', points: 5 },
  { id: 'bom-quilon', a: 'bombay', b: 'quilon', points: 6 },
  { id: 'cal-erode', a: 'calcutta', b: 'erode', points: 9 },
  { id: 'cal-indur', a: 'calcutta', b: 'indur', points: 8 },
  { id: 'chi-wadi', a: 'chittagong', b: 'wadi', points: 11 },
  { id: 'del-calicut', a: 'delhi', b: 'calicut', points: 11 },
  { id: 'del-chittagong', a: 'delhi', b: 'chittagong', points: 9 },
  { id: 'del-indur', a: 'delhi', b: 'indur', points: 9 },
  { id: 'dhu-mangalore', a: 'dhubri', b: 'mangalore', points: 12 },
  { id: 'jac-bombay', a: 'jacobabad', b: 'bombay', points: 10 },
  { id: 'jac-calcutta', a: 'jacobabad', b: 'calcutta', points: 13 },
  { id: 'jac-ratiam', a: 'jacobabad', b: 'ratiam', points: 9 },
  { id: 'jai-patna', a: 'jaipur', b: 'patna', points: 5 },
  { id: 'jai-poona', a: 'jaipur', b: 'poona', points: 5 },
  { id: 'jai-raipur', a: 'jaipur', b: 'raipur', points: 5 },
  { id: 'jar-bombay', a: 'jarhat', b: 'bombay', points: 13 },
  { id: 'jod-guntakal', a: 'jodhpur', b: 'guntakal', points: 9 },
  { id: 'jod-khandwa', a: 'jodhpur', b: 'khandwa', points: 5 },
  { id: 'jod-lucknow', a: 'jodhpur', b: 'lucknow', points: 5 },
  { id: 'kar-ahm', a: 'karachi', b: 'ahmadabad', points: 6 },
  { id: 'kar-delhi', a: 'karachi', b: 'delhi', points: 7 },
  { id: 'kar-poona', a: 'karachi', b: 'poona', points: 7 },
  { id: 'kat-khandwa', a: 'katni', b: 'khandwa', points: 5 },
  { id: 'kat-wadi', a: 'katni', b: 'wadi', points: 8 },
  { id: 'kat-waltain', a: 'katni', b: 'waltain', points: 5 },
  { id: 'kha-chittagong', a: 'khandwa', b: 'chittagong', points: 10 },
  { id: 'lah-delhi', a: 'lahore', b: 'delhi', points: 5 },
  { id: 'lah-dhubri', a: 'lahore', b: 'dhubri', points: 12 },
  { id: 'lah-wadi', a: 'lahore', b: 'wadi', points: 13 },
  { id: 'luc-bombay', a: 'lucknow', b: 'bombay', points: 7 },
  { id: 'luc-erode', a: 'lucknow', b: 'erode', points: 11 },
  { id: 'man-erode', a: 'manmad', b: 'erode', points: 7 },
  { id: 'mad-quilon', a: 'madras', b: 'quilon', points: 6 },
  { id: 'pat-madras', a: 'patna', b: 'madras', points: 9 },
  { id: 'pat-mormugao', a: 'patna', b: 'mormugao', points: 10 },
  { id: 'pes-bhopal', a: 'peshawar', b: 'bhopal', points: 9 },
  { id: 'pes-madras', a: 'peshawar', b: 'madras', points: 17 },
  { id: 'rai-guntakal', a: 'raipur', b: 'guntakal', points: 7 },
  { id: 'rai-manmad', a: 'raipur', b: 'manmad', points: 5 },
  { id: 'rat-bezwada', a: 'ratiam', b: 'bezwada', points: 8 },
  { id: 'roh-agra', a: 'rohri', b: 'agra', points: 7 },
  { id: 'roh-mangalore', a: 'rohri', b: 'mangalore', points: 12 },
  { id: 'wal-mangalore', a: 'waltain', b: 'mangalore', points: 6 },
];

export const TTR_INDIA_MAP: TtrMapDefinition = {
  id: 'india',
  name: 'India',
  minPlayers: 2,
  maxPlayers: 4,
  trainsPerPlayer: 45,
  stationsPerPlayer: 0,
  unplacedStationBonus: 0,
  routePoints: TTR_ROUTE_POINTS,
  deck: { cardsPerColor: 12, locomotives: 14 },
  setup: {
    trainCards: 4,
    /** India has no Long-ticket pile — keep threshold above any ticket points. */
    longTicketThreshold: 99,
    initialLongTickets: 0,
    initialRegularTickets: 4,
    minInitialKeep: 2,
    longTicketsMandatory: false,
    ticketDraw: 3,
    minTicketKeep: 1,
  },
  rules: {
    doubleRouteLockMaxPlayers: 3,
    oneRoutePerGroupPerPlayer: true,
    faceUpCount: 5,
    faceUpLocomotiveReset: 3,
    endgameTrainThreshold: 2,
    longestPathBonus: 10,
    mandalaBonus: true,
    tiebreak: 'longest-path',
  },
  cities: CITIES,
  routes: ROUTES,
  destinationTickets: DESTINATION_TICKETS,
};
