import {
  TTR_ROUTE_POINTS,
  ttrRouteGroupId,
  type TtrCityDef,
  type TtrDestinationTicket,
  type TtrMapDefinition,
  type TtrRouteColor,
  type TtrRouteDef,
} from '../model.js';

/**
 * Ticket to Ride — Japan (Map Collection 7).
 *
 * Bullet Train corridors use shared-network rules while white miniatures remain
 * (16 supply): pay like gray, place one BT, advance progression, no route points /
 * no colored trains. Claimed BT edges help every player's tickets. After supply
 * runs out, leftover corridors claim as exclusive gray. Endgame needs both
 * colored trains ≤2 and BT supply ≤2. Final score includes BT bonus by progression.
 *
 * Route lengths/colors are best-effort from board art (`map-japan_vc7lwd`) —
 * refine via `/dev/ticket-to-ride-layout` and play QA.
 *
 * Tokyo / Kokura: one city id each; inset routes attach to the same id.
 * Aomori–Hakodate unequal lengths use distinct group ids (not a double).
 */
const CITIES: readonly TtrCityDef[] = [
  // Main board
  { id: 'hakodate', name: 'Hakodate' },
  { id: 'aomori', name: 'Aomori' },
  { id: 'akita', name: 'Akita' },
  { id: 'morioka', name: 'Morioka' },
  { id: 'miyako', name: 'Miyako' },
  { id: 'shinjo', name: 'Shinjō' },
  { id: 'sendai', name: 'Sendai' },
  { id: 'niigata', name: 'Niigata' },
  { id: 'fukushima', name: 'Fukushima' },
  { id: 'iwaki', name: 'Iwaki' },
  { id: 'utsunomiya', name: 'Utsunomiya' },
  { id: 'takasaki', name: 'Takasaki' },
  { id: 'nagano', name: 'Nagano' },
  { id: 'matsumoto', name: 'Matsumoto' },
  { id: 'kanazawa', name: 'Kanazawa' },
  { id: 'tsuruga', name: 'Tsuruga' },
  { id: 'tokyo', name: 'Tokyo' },
  { id: 'narita', name: 'Narita' },
  { id: 'odawara', name: 'Odawara' },
  { id: 'hamamatsu', name: 'Hamamatsu' },
  { id: 'nagoya', name: 'Nagoya' },
  { id: 'ise', name: 'Ise' },
  { id: 'kyoto', name: 'Kyoto' },
  { id: 'osaka', name: 'Osaka' },
  { id: 'tottori', name: 'Tottori' },
  { id: 'okayama', name: 'Okayama' },
  { id: 'hiroshima', name: 'Hiroshima' },
  { id: 'masuda', name: 'Masuda' },
  { id: 'matsuyama', name: 'Matsuyama' },
  { id: 'takamatsu', name: 'Takamatsu' },
  { id: 'kochi', name: 'Kōchi' },
  { id: 'kokura', name: 'Kokura' },
  // Kyushu inset (kokura/hakata shared with main)
  { id: 'hakata', name: 'Hakata' },
  { id: 'nagasaki', name: 'Nagasaki' },
  { id: 'kumamoto', name: 'Kumamoto' },
  { id: 'oita', name: 'Ōita' },
  { id: 'miyazaki', name: 'Miyazaki' },
  { id: 'kagoshima-chuo', name: 'Kagoshima-Chūō' },
  // Tokyo subway inset
  { id: 'ikebukuro', name: 'Ikebukuro' },
  { id: 'ueno', name: 'Ueno' },
  { id: 'kita-senju', name: 'Kita-Senju' },
  { id: 'asakusa', name: 'Asakusa' },
  { id: 'suitengumae', name: 'Suitengūmae' },
  { id: 'monzen-nakacho', name: 'Monzen-Nakachō' },
  { id: 'ginza', name: 'Ginza' },
  { id: 'yotsuya', name: 'Yotsuya' },
  { id: 'shinjuku', name: 'Shinjuku' },
  { id: 'shibuya', name: 'Shibuya' },
];

/** [id, a, b, length, color, bulletTrain?] */
type RouteRow = readonly [
  id: string,
  a: string,
  b: string,
  length: number,
  color: TtrRouteColor,
  bulletTrain?: boolean,
];

const ROUTE_ROWS: readonly RouteRow[] = [
  // ── Hokkaido / north Honshu ────────────────────────────────
  // Unequal Aomori–Hakodate: NOT a double group
  ['hak-aom-short', 'hakodate', 'aomori', 2, 'gray', true],
  ['hak-aom-long', 'hakodate', 'aomori', 3, 'white'],
  ['aom-aki', 'aomori', 'akita', 3, 'red'],
  ['aom-mor', 'aomori', 'morioka', 4, 'gray', true],
  ['aom-miy', 'aomori', 'miyako', 5, 'yellow'],
  ['aki-mor', 'akita', 'morioka', 2, 'gray', true],
  ['aki-shi', 'akita', 'shinjo', 2, 'blue'],
  ['mor-miy', 'morioka', 'miyako', 1, 'black'],
  ['mor-sen', 'morioka', 'sendai', 4, 'gray', true],
  ['mor-shi', 'morioka', 'shinjo', 3, 'green'],
  ['shi-sen', 'shinjo', 'sendai', 2, 'white'],
  ['shi-nii', 'shinjo', 'niigata', 3, 'black'],
  ['sen-fuk', 'sendai', 'fukushima', 1, 'gray', true],
  ['sen-iwa', 'sendai', 'iwaki', 3, 'blue'],
  ['miy-sen', 'miyako', 'sendai', 5, 'purple'],
  ['nii-aki', 'niigata', 'akita', 5, 'orange'],

  // ── East / Kanto approaches ────────────────────────────────
  ['fuk-uts', 'fukushima', 'utsunomiya', 3, 'gray', true],
  ['fuk-iwa', 'fukushima', 'iwaki', 2, 'green'],
  ['fuk-nii', 'fukushima', 'niigata', 3, 'red'],
  ['fuk-shi', 'fukushima', 'shinjo', 3, 'gray', true],
  ['uts-nar', 'utsunomiya', 'narita', 2, 'yellow'],
  ['uts-tok', 'utsunomiya', 'tokyo', 2, 'gray', true],
  ['uts-tak', 'utsunomiya', 'takasaki', 2, 'blue'],
  ['nar-tok-1', 'narita', 'tokyo', 1, 'orange'],
  ['nar-tok-2', 'narita', 'tokyo', 1, 'purple'],
  ['nar-iwa', 'narita', 'iwaki', 3, 'white'],
  ['tak-tok', 'takasaki', 'tokyo', 2, 'gray', true],
  ['tak-nag', 'takasaki', 'nagano', 2, 'gray', true],
  ['nii-tak', 'niigata', 'takasaki', 4, 'gray', true],
  ['nii-nag', 'niigata', 'nagano', 4, 'purple'],

  // ── Central Alps / Hokuriku ─────────────────────────────────
  ['nag-mat', 'nagano', 'matsumoto', 1, 'yellow'],
  ['nag-kan', 'nagano', 'kanazawa', 4, 'gray', true],
  ['mat-tok', 'matsumoto', 'tokyo', 4, 'black'],
  ['mat-oda', 'matsumoto', 'odawara', 4, 'green'],
  ['mat-nagoya-1', 'matsumoto', 'nagoya', 3, 'blue'],
  ['mat-nagoya-2', 'matsumoto', 'nagoya', 3, 'red'],
  ['kan-tsu', 'kanazawa', 'tsuruga', 3, 'white'],
  ['kan-nagoya', 'kanazawa', 'nagoya', 4, 'orange'],
  ['tsu-kyo', 'tsuruga', 'kyoto', 1, 'black'],
  ['tsu-nagoya', 'tsuruga', 'nagoya', 2, 'purple'],
  ['tot-tsu', 'tottori', 'tsuruga', 4, 'blue'],

  // ── Tokaido / Chuo corridor (BT spine) ─────────────────────
  ['tok-oda', 'tokyo', 'odawara', 1, 'gray', true],
  ['oda-ham', 'odawara', 'hamamatsu', 3, 'gray', true],
  ['ham-nagoya', 'hamamatsu', 'nagoya', 3, 'gray', true],
  ['nagoya-kyo', 'nagoya', 'kyoto', 2, 'gray', true],
  ['nagoya-ise', 'nagoya', 'ise', 2, 'white'],
  ['kyo-ise', 'kyoto', 'ise', 2, 'orange'],
  ['ise-osa', 'ise', 'osaka', 3, 'yellow'],
  ['kyo-osa', 'kyoto', 'osaka', 1, 'gray', true],

  // ── Kansai / Chugoku / Shikoku ─────────────────────────────
  ['osa-oka', 'osaka', 'okayama', 3, 'gray', true],
  ['osa-takamatsu', 'osaka', 'takamatsu', 3, 'purple'],
  ['osa-tot', 'osaka', 'tottori', 3, 'red'],
  ['kyo-tot', 'kyoto', 'tottori', 4, 'green'],
  ['tot-oka', 'tottori', 'okayama', 2, 'white'],
  ['tot-mas', 'tottori', 'masuda', 6, 'black'],
  ['oka-hir', 'okayama', 'hiroshima', 3, 'gray', true],
  ['oka-takamatsu-1', 'okayama', 'takamatsu', 1, 'yellow'],
  ['oka-takamatsu-2', 'okayama', 'takamatsu', 1, 'red'],
  ['hir-mas-1', 'hiroshima', 'masuda', 1, 'red'],
  ['hir-mas-2', 'hiroshima', 'masuda', 1, 'white'],
  ['hir-kok', 'hiroshima', 'kokura', 4, 'gray', true],
  ['kok-mat', 'kokura', 'matsuyama', 4, 'gray'],
  ['hir-mat-1', 'hiroshima', 'matsuyama', 1, 'black'],
  ['hir-mat-2', 'hiroshima', 'matsuyama', 1, 'purple'],
  ['mas-kok-1', 'masuda', 'kokura', 3, 'yellow'],
  ['mas-kok-2', 'masuda', 'kokura', 3, 'green'],
  ['takamatsu-mat', 'takamatsu', 'matsuyama', 3, 'blue'],
  ['takamatsu-kochi', 'takamatsu', 'kochi', 2, 'orange'],
  ['mat-kochi', 'matsuyama', 'kochi', 2, 'green'],

  // ── Kyushu inset (kokura/hakata shared hubs) ───────────────
  ['kok-hak', 'kokura', 'hakata', 1, 'gray', true],
  ['kok-oit-1', 'kokura', 'oita', 2, 'orange'],
  ['kok-oit-2', 'kokura', 'oita', 2, 'purple'],
  ['hak-nag-1', 'hakata', 'nagasaki', 2, 'orange'],
  ['hak-nag-2', 'hakata', 'nagasaki', 2, 'white'],
  ['hak-kum', 'hakata', 'kumamoto', 2, 'gray', true],
  ['nag-kum-1', 'nagasaki', 'kumamoto', 1, 'green'],
  ['nag-kum-2', 'nagasaki', 'kumamoto', 1, 'black'],
  ['kum-oit-1', 'kumamoto', 'oita', 2, 'red'],
  ['kum-oit-2', 'kumamoto', 'oita', 2, 'blue'],
  ['kum-miy', 'kumamoto', 'miyazaki', 3, 'purple'],
  ['kum-kag', 'kumamoto', 'kagoshima-chuo', 3, 'gray', true],
  ['oit-miy', 'oita', 'miyazaki', 4, 'white'],
  ['miy-kag', 'miyazaki', 'kagoshima-chuo', 2, 'yellow'],

  // ── Tokyo subway inset ─────────────────────────────────────
  ['tk-ike-uen-1', 'ikebukuro', 'ueno', 3, 'yellow'],
  ['tk-ike-uen-2', 'ikebukuro', 'ueno', 3, 'black'],
  ['tk-ike-sin-1', 'ikebukuro', 'shinjuku', 3, 'green'],
  ['tk-ike-sin-2', 'ikebukuro', 'shinjuku', 3, 'orange'],
  ['tk-ike-yot', 'ikebukuro', 'yotsuya', 2, 'red'],
  ['tk-sin-yot-1', 'shinjuku', 'yotsuya', 2, 'purple'],
  ['tk-sin-yot-2', 'shinjuku', 'yotsuya', 2, 'white'],
  ['tk-sin-shi-1', 'shinjuku', 'shibuya', 2, 'blue'],
  ['tk-sin-shi-2', 'shinjuku', 'shibuya', 2, 'black'],
  ['tk-shi-yot-1', 'shibuya', 'yotsuya', 2, 'green'],
  ['tk-shi-tok-1', 'shibuya', 'tokyo', 3, 'orange'],
  ['tk-shi-tok-2', 'shibuya', 'tokyo', 3, 'red'],
  ['tk-yot-tok-1', 'yotsuya', 'tokyo', 1, 'blue'],
  ['tk-yot-tok-2', 'yotsuya', 'tokyo', 1, 'yellow'],
  ['tk-tok-gin-1', 'tokyo', 'ginza', 1, 'gray', true],
  ['tk-tok-uen-1', 'tokyo', 'ueno', 2, 'green'],
  ['tk-tok-uen-2', 'tokyo', 'ueno', 2, 'purple'],
  ['tk-tok-sui-1', 'tokyo', 'suitengumae', 2, 'white'],
  ['tk-tok-sui-2', 'tokyo', 'suitengumae', 2, 'black'],
  ['tk-uen-kit-1', 'ueno', 'kita-senju', 2, 'white'],
  ['tk-uen-kit-2', 'ueno', 'kita-senju', 2, 'red'],
  ['tk-uen-sui', 'ueno', 'suitengumae', 2, 'orange'],
  ['tk-kit-asa-1', 'kita-senju', 'asakusa', 1, 'orange'],
  ['tk-kit-asa-2', 'kita-senju', 'asakusa', 1, 'black'],
  ['tk-asa-sui-1', 'asakusa', 'suitengumae', 2, 'green'],
  ['tk-asa-sui-2', 'asakusa', 'suitengumae', 2, 'yellow'],
  ['tk-asa-mon', 'asakusa', 'monzen-nakacho', 3, 'blue'],
  ['tk-sui-mon-1', 'suitengumae', 'monzen-nakacho', 2, 'red'],
  ['tk-sui-mon-2', 'suitengumae', 'monzen-nakacho', 2, 'purple'],
  ['tk-sui-gin', 'suitengumae', 'ginza', 2, 'blue'],
  ['tk-mon-gin', 'monzen-nakacho', 'ginza', 3, 'yellow'],
];

const ROUTES: readonly TtrRouteDef[] = ROUTE_ROWS.map(([id, a, b, length, color, bulletTrain]) => {
  // Unequal Aomori–Hakodate must not share a group (not a double route).
  const groupId = id === 'hak-aom-short' || id === 'hak-aom-long' ? id : ttrRouteGroupId(a, b);
  return {
    id,
    a,
    b,
    length,
    color,
    groupId,
    ...(bulletTrain ? { bulletTrain: true } : {}),
  };
});

/** 54 destination tickets from the Japan Map Collection deck. */
const DESTINATION_TICKETS: readonly TtrDestinationTicket[] = [
  { id: 'sendai-aomori', a: 'sendai', b: 'aomori', points: 4 },
  { id: 'shibuya-ueno', a: 'shibuya', b: 'ueno', points: 7 },
  { id: 'masuda-sendai', a: 'masuda', b: 'sendai', points: 16 },
  { id: 'nagano-suitengumae', a: 'nagano', b: 'suitengumae', points: 6 },
  { id: 'matsumoto-fukushima', a: 'matsumoto', b: 'fukushima', points: 5 },
  { id: 'ikebukuro-suitengumae', a: 'ikebukuro', b: 'suitengumae', points: 7 },
  { id: 'akita-miyako', a: 'akita', b: 'miyako', points: 2 },
  { id: 'shinjuku-ikebukuro', a: 'shinjuku', b: 'ikebukuro', points: 4 },
  { id: 'nagasaki-niigata', a: 'nagasaki', b: 'niigata', points: 16 },
  { id: 'takasaki-morioka', a: 'takasaki', b: 'morioka', points: 5 },
  { id: 'kumamoto-takamatsu', a: 'kumamoto', b: 'takamatsu', points: 7 },
  { id: 'hamamatsu-utsunomiya', a: 'hamamatsu', b: 'utsunomiya', points: 3 },
  { id: 'okayama-matsumoto', a: 'okayama', b: 'matsumoto', points: 6 },
  { id: 'hiroshima-hakodate', a: 'hiroshima', b: 'hakodate', points: 14 },
  { id: 'odawara-narita', a: 'odawara', b: 'narita', points: 1 },
  { id: 'kokura-tsuruga', a: 'kokura', b: 'tsuruga', points: 8 },
  { id: 'hakata-ise', a: 'hakata', b: 'ise', points: 14 },
  { id: 'yotsuya-monzen-nakacho', a: 'yotsuya', b: 'monzen-nakacho', points: 7 },
  { id: 'hakata-miyako', a: 'hakata', b: 'miyako', points: 19 },
  { id: 'shinjuku-asakusa', a: 'shinjuku', b: 'asakusa', points: 10 },
  { id: 'hakata-kanazawa', a: 'hakata', b: 'kanazawa', points: 8 },
  { id: 'kagoshima-chuo-kokura', a: 'kagoshima-chuo', b: 'kokura', points: 3 },
  { id: 'ginza-kita-senju', a: 'ginza', b: 'kita-senju', points: 7 },
  { id: 'nagasaki-miyazaki', a: 'nagasaki', b: 'miyazaki', points: 5 },
  { id: 'nagoya-shinjuku', a: 'nagoya', b: 'shinjuku', points: 10 },
  { id: 'nagoya-shinjo', a: 'nagoya', b: 'shinjo', points: 7 },
  { id: 'matsuyama-nagoya', a: 'matsuyama', b: 'nagoya', points: 6 },
  { id: 'tottori-nagoya', a: 'tottori', b: 'nagoya', points: 4 },
  { id: 'nagasaki-nagoya', a: 'nagasaki', b: 'nagoya', points: 10 },
  { id: 'hakata-oita', a: 'hakata', b: 'oita', points: 3 },
  { id: 'nagoya-iwaki', a: 'nagoya', b: 'iwaki', points: 8 },
  { id: 'hakata-kochi', a: 'hakata', b: 'kochi', points: 8 },
  { id: 'kyoto-niigata', a: 'kyoto', b: 'niigata', points: 5 },
  { id: 'osaka-shibuya', a: 'osaka', b: 'shibuya', points: 13 },
  { id: 'kyoto-narita', a: 'kyoto', b: 'narita', points: 6 },
  { id: 'miyazaki-kyoto', a: 'miyazaki', b: 'kyoto', points: 12 },
  { id: 'kyoto-aomori', a: 'kyoto', b: 'aomori', points: 9 },
  { id: 'masuda-kyoto', a: 'masuda', b: 'kyoto', points: 5 },
  { id: 'kyoto-ikebukuro', a: 'kyoto', b: 'ikebukuro', points: 12 },
  { id: 'kochi-kyoto', a: 'kochi', b: 'kyoto', points: 6 },
  { id: 'tokyo-asakusa', a: 'tokyo', b: 'asakusa', points: 6 },
  { id: 'kagoshima-chuo-osaka', a: 'kagoshima-chuo', b: 'osaka', points: 8 },
  { id: 'ise-tokyo', a: 'ise', b: 'tokyo', points: 6 },
  { id: 'osaka-nagano', a: 'osaka', b: 'nagano', points: 3 },
  { id: 'hakata-tokyo', a: 'hakata', b: 'tokyo', points: 10 },
  { id: 'osaka-fukushima', a: 'osaka', b: 'fukushima', points: 7 },
  { id: 'hiroshima-osaka', a: 'hiroshima', b: 'osaka', points: 3 },
  { id: 'osaka-akita', a: 'osaka', b: 'akita', points: 9 },
  { id: 'tokyo-hakodate', a: 'tokyo', b: 'hakodate', points: 8 },
  { id: 'osaka-tokyo', a: 'osaka', b: 'tokyo', points: 5 },
  { id: 'tokyo-sendai', a: 'tokyo', b: 'sendai', points: 3 },
  { id: 'tottori-tokyo', a: 'tottori', b: 'tokyo', points: 9 },
  { id: 'kagoshima-chuo-tokyo', a: 'kagoshima-chuo', b: 'tokyo', points: 13 },
  { id: 'tokyo-shinjuku', a: 'tokyo', b: 'shinjuku', points: 4 },
];

export const TTR_JAPAN_MAP: TtrMapDefinition = {
  id: 'japan',
  name: 'Japan',
  minPlayers: 2,
  maxPlayers: 5,
  trainsPerPlayer: 20,
  stationsPerPlayer: 0,
  unplacedStationBonus: 0,
  routePoints: TTR_ROUTE_POINTS,
  deck: { cardsPerColor: 12, locomotives: 14 },
  setup: {
    trainCards: 4,
    /** No Long pile on Japan. */
    longTicketThreshold: 99,
    initialLongTickets: 0,
    initialRegularTickets: 4,
    minInitialKeep: 2,
    longTicketsMandatory: false,
    ticketDraw: 3,
    minTicketKeep: 1,
  },
  rules: {
    doubleRouteLockMaxPlayers: 3,
    oneRoutePerGroupPerPlayer: true,
    faceUpCount: 5,
    faceUpLocomotiveReset: 3,
    endgameTrainThreshold: 2,
    longestPathBonus: 0,
    bulletTrainMiniatures: 16,
    tiebreak: 'longest-path',
  },
  cities: CITIES,
  routes: ROUTES,
  destinationTickets: DESTINATION_TICKETS,
};
