import {
  TTR_ROUTE_POINTS,
  ttrRouteGroupId,
  type TtrCityDef,
  type TtrDestinationTicket,
  type TtrMapDefinition,
  type TtrRouteColor,
  type TtrRouteDef,
} from '../model.js';

const CITIES: readonly TtrCityDef[] = [
  { id: 'vancouver', name: 'Vancouver' },
  { id: 'seattle', name: 'Seattle' },
  { id: 'portland', name: 'Portland' },
  { id: 'calgary', name: 'Calgary' },
  { id: 'helena', name: 'Helena' },
  { id: 'winnipeg', name: 'Winnipeg' },
  { id: 'duluth', name: 'Duluth' },
  { id: 'sault-ste-marie', name: 'Sault Ste. Marie' },
  { id: 'montreal', name: 'Montreal' },
  { id: 'toronto', name: 'Toronto' },
  { id: 'boston', name: 'Boston' },
  { id: 'new-york', name: 'New York' },
  { id: 'pittsburgh', name: 'Pittsburgh' },
  { id: 'washington', name: 'Washington' },
  { id: 'chicago', name: 'Chicago' },
  { id: 'omaha', name: 'Omaha' },
  { id: 'denver', name: 'Denver' },
  { id: 'salt-lake-city', name: 'Salt Lake City' },
  { id: 'san-francisco', name: 'San Francisco' },
  { id: 'las-vegas', name: 'Las Vegas' },
  { id: 'los-angeles', name: 'Los Angeles' },
  { id: 'phoenix', name: 'Phoenix' },
  { id: 'santa-fe', name: 'Santa Fe' },
  { id: 'el-paso', name: 'El Paso' },
  { id: 'oklahoma-city', name: 'Oklahoma City' },
  { id: 'kansas-city', name: 'Kansas City' },
  { id: 'saint-louis', name: 'Saint Louis' },
  { id: 'little-rock', name: 'Little Rock' },
  { id: 'nashville', name: 'Nashville' },
  { id: 'raleigh', name: 'Raleigh' },
  { id: 'charleston', name: 'Charleston' },
  { id: 'atlanta', name: 'Atlanta' },
  { id: 'miami', name: 'Miami' },
  { id: 'new-orleans', name: 'New Orleans' },
  { id: 'houston', name: 'Houston' },
  { id: 'dallas', name: 'Dallas' },
];

type RouteRow = readonly [id: string, a: string, b: string, length: number, color: TtrRouteColor];

/** Parallel tracks are separate rows; the group id is derived from the city pair. */
const ROUTE_ROWS: readonly RouteRow[] = [
  ['sea-por-1', 'seattle', 'portland', 1, 'gray'],
  ['sea-por-2', 'seattle', 'portland', 1, 'gray'],
  ['sea-van-1', 'seattle', 'vancouver', 1, 'gray'],
  ['sea-van-2', 'seattle', 'vancouver', 1, 'gray'],
  ['sea-cal', 'seattle', 'calgary', 4, 'gray'],
  ['sea-hel', 'seattle', 'helena', 6, 'yellow'],
  ['van-cal', 'vancouver', 'calgary', 3, 'gray'],
  ['por-sf-1', 'portland', 'san-francisco', 5, 'purple'],
  ['por-sf-2', 'portland', 'san-francisco', 5, 'green'],
  ['por-slc', 'portland', 'salt-lake-city', 6, 'blue'],
  ['sf-la-1', 'san-francisco', 'los-angeles', 3, 'purple'],
  ['sf-la-2', 'san-francisco', 'los-angeles', 3, 'yellow'],
  ['slc-sf-1', 'salt-lake-city', 'san-francisco', 5, 'white'],
  ['slc-sf-2', 'salt-lake-city', 'san-francisco', 5, 'orange'],
  ['slc-den-1', 'salt-lake-city', 'denver', 3, 'red'],
  ['slc-den-2', 'salt-lake-city', 'denver', 3, 'yellow'],
  ['slc-hel', 'salt-lake-city', 'helena', 3, 'purple'],
  ['lv-slc', 'las-vegas', 'salt-lake-city', 3, 'orange'],
  ['la-lv', 'los-angeles', 'las-vegas', 2, 'gray'],
  ['la-phx', 'los-angeles', 'phoenix', 3, 'gray'],
  ['la-elp', 'los-angeles', 'el-paso', 6, 'black'],
  ['phx-sfe', 'phoenix', 'santa-fe', 3, 'gray'],
  ['phx-den', 'phoenix', 'denver', 5, 'white'],
  ['phx-elp', 'phoenix', 'el-paso', 3, 'gray'],
  ['sfe-den', 'santa-fe', 'denver', 2, 'gray'],
  ['sfe-okc', 'santa-fe', 'oklahoma-city', 3, 'blue'],
  ['sfe-elp', 'santa-fe', 'el-paso', 2, 'gray'],
  ['elp-okc', 'el-paso', 'oklahoma-city', 5, 'yellow'],
  ['elp-hou', 'el-paso', 'houston', 6, 'green'],
  ['elp-dal', 'el-paso', 'dallas', 4, 'red'],
  ['cal-hel', 'calgary', 'helena', 4, 'gray'],
  ['cal-win', 'calgary', 'winnipeg', 6, 'white'],
  ['hel-win', 'helena', 'winnipeg', 4, 'blue'],
  ['hel-oma', 'helena', 'omaha', 5, 'red'],
  ['hel-den', 'helena', 'denver', 4, 'green'],
  ['hel-dul', 'helena', 'duluth', 6, 'orange'],
  ['den-oma', 'denver', 'omaha', 4, 'purple'],
  ['den-kc-1', 'denver', 'kansas-city', 4, 'black'],
  ['den-kc-2', 'denver', 'kansas-city', 4, 'orange'],
  ['den-okc', 'denver', 'oklahoma-city', 4, 'red'],
  ['win-sau', 'winnipeg', 'sault-ste-marie', 6, 'gray'],
  ['win-dul', 'winnipeg', 'duluth', 4, 'black'],
  ['dul-sau', 'duluth', 'sault-ste-marie', 3, 'gray'],
  ['dul-oma-1', 'duluth', 'omaha', 2, 'gray'],
  ['dul-oma-2', 'duluth', 'omaha', 2, 'gray'],
  ['dul-tor', 'duluth', 'toronto', 6, 'purple'],
  ['dul-chi', 'duluth', 'chicago', 3, 'red'],
  ['oma-chi', 'omaha', 'chicago', 4, 'blue'],
  ['oma-kc-1', 'omaha', 'kansas-city', 1, 'gray'],
  ['oma-kc-2', 'omaha', 'kansas-city', 1, 'gray'],
  ['kc-stl-1', 'kansas-city', 'saint-louis', 2, 'blue'],
  ['kc-stl-2', 'kansas-city', 'saint-louis', 2, 'purple'],
  ['kc-okc-1', 'kansas-city', 'oklahoma-city', 2, 'gray'],
  ['kc-okc-2', 'kansas-city', 'oklahoma-city', 2, 'gray'],
  ['okc-dal-1', 'oklahoma-city', 'dallas', 2, 'gray'],
  ['okc-dal-2', 'oklahoma-city', 'dallas', 2, 'gray'],
  ['okc-lr', 'oklahoma-city', 'little-rock', 2, 'white'],
  ['dal-lr', 'dallas', 'little-rock', 2, 'gray'],
  ['dal-hou-1', 'dallas', 'houston', 1, 'gray'],
  ['dal-hou-2', 'dallas', 'houston', 1, 'gray'],
  ['no-hou', 'new-orleans', 'houston', 2, 'gray'],
  ['sau-tor', 'sault-ste-marie', 'toronto', 2, 'gray'],
  ['sau-mtl', 'sault-ste-marie', 'montreal', 5, 'black'],
  ['mtl-bos-1', 'montreal', 'boston', 2, 'gray'],
  ['mtl-bos-2', 'montreal', 'boston', 2, 'gray'],
  ['mtl-ny', 'montreal', 'new-york', 3, 'blue'],
  ['tor-mtl', 'toronto', 'montreal', 3, 'gray'],
  ['tor-pit', 'toronto', 'pittsburgh', 2, 'gray'],
  ['tor-chi', 'toronto', 'chicago', 4, 'white'],
  ['chi-pit-1', 'chicago', 'pittsburgh', 3, 'orange'],
  ['chi-pit-2', 'chicago', 'pittsburgh', 3, 'black'],
  ['stl-pit', 'saint-louis', 'pittsburgh', 5, 'green'],
  ['chi-stl-1', 'chicago', 'saint-louis', 2, 'white'],
  ['chi-stl-2', 'chicago', 'saint-louis', 2, 'green'],
  ['stl-lr', 'saint-louis', 'little-rock', 2, 'gray'],
  ['pit-ny-1', 'pittsburgh', 'new-york', 2, 'white'],
  ['pit-ny-2', 'pittsburgh', 'new-york', 2, 'green'],
  ['pit-was', 'pittsburgh', 'washington', 2, 'gray'],
  ['pit-nas', 'pittsburgh', 'nashville', 4, 'yellow'],
  ['was-ral-1', 'washington', 'raleigh', 2, 'gray'],
  ['was-ral-2', 'washington', 'raleigh', 2, 'gray'],
  ['was-ny-1', 'washington', 'new-york', 2, 'orange'],
  ['was-ny-2', 'washington', 'new-york', 2, 'black'],
  ['ny-bos-1', 'new-york', 'boston', 2, 'yellow'],
  ['ny-bos-2', 'new-york', 'boston', 2, 'red'],
  ['ral-pit', 'raleigh', 'pittsburgh', 2, 'gray'],
  ['ral-atl-1', 'raleigh', 'atlanta', 2, 'gray'],
  ['ral-atl-2', 'raleigh', 'atlanta', 2, 'gray'],
  ['ral-cha', 'raleigh', 'charleston', 2, 'gray'],
  ['miami-cha', 'miami', 'charleston', 4, 'purple'],
  ['atl-cha', 'atlanta', 'charleston', 2, 'gray'],
  ['atl-mia', 'atlanta', 'miami', 5, 'blue'],
  ['no-mia', 'new-orleans', 'miami', 6, 'red'],
  ['atl-no-1', 'atlanta', 'new-orleans', 4, 'orange'],
  ['atl-no-2', 'atlanta', 'new-orleans', 4, 'yellow'],
  ['stl-nas', 'saint-louis', 'nashville', 2, 'gray'],
  ['nas-atl', 'nashville', 'atlanta', 1, 'gray'],
  ['nas-lr', 'nashville', 'little-rock', 3, 'white'],
  ['nas-ral', 'nashville', 'raleigh', 3, 'black'],
  ['lr-no', 'little-rock', 'new-orleans', 3, 'green'],
];

const ROUTES: readonly TtrRouteDef[] = ROUTE_ROWS.map(([id, a, b, length, color]) => ({
  id,
  a,
  b,
  length,
  color,
  groupId: ttrRouteGroupId(a, b),
}));

const DESTINATION_TICKETS: readonly TtrDestinationTicket[] = [
  { id: 'bos-mia', a: 'boston', b: 'miami', points: 12 },
  { id: 'cal-phx', a: 'calgary', b: 'phoenix', points: 13 },
  { id: 'cal-slc', a: 'calgary', b: 'salt-lake-city', points: 7 },
  { id: 'chi-no', a: 'chicago', b: 'new-orleans', points: 7 },
  { id: 'chi-sfe', a: 'chicago', b: 'santa-fe', points: 9 },
  { id: 'dal-ny', a: 'dallas', b: 'new-york', points: 11 },
  { id: 'den-elp', a: 'denver', b: 'el-paso', points: 4 },
  { id: 'den-pit', a: 'denver', b: 'pittsburgh', points: 11 },
  { id: 'dul-elp', a: 'duluth', b: 'el-paso', points: 10 },
  { id: 'dul-hou', a: 'duluth', b: 'houston', points: 8 },
  { id: 'hel-la', a: 'helena', b: 'los-angeles', points: 8 },
  { id: 'kc-hou', a: 'kansas-city', b: 'houston', points: 5 },
  { id: 'la-chi', a: 'los-angeles', b: 'chicago', points: 16 },
  { id: 'la-mia', a: 'los-angeles', b: 'miami', points: 20 },
  { id: 'la-ny', a: 'los-angeles', b: 'new-york', points: 21 },
  { id: 'mtl-atl', a: 'montreal', b: 'atlanta', points: 9 },
  { id: 'mtl-no', a: 'montreal', b: 'new-orleans', points: 13 },
  { id: 'ny-atl', a: 'new-york', b: 'atlanta', points: 6 },
  { id: 'por-nas', a: 'portland', b: 'nashville', points: 17 },
  { id: 'por-phx', a: 'portland', b: 'phoenix', points: 11 },
  { id: 'sf-atl', a: 'san-francisco', b: 'atlanta', points: 17 },
  { id: 'sau-nas', a: 'sault-ste-marie', b: 'nashville', points: 8 },
  { id: 'sau-okc', a: 'sault-ste-marie', b: 'oklahoma-city', points: 9 },
  { id: 'sea-la', a: 'seattle', b: 'los-angeles', points: 9 },
  { id: 'sea-ny', a: 'seattle', b: 'new-york', points: 22 },
  { id: 'tor-mia', a: 'toronto', b: 'miami', points: 10 },
  { id: 'van-mtl', a: 'vancouver', b: 'montreal', points: 20 },
  { id: 'van-sfe', a: 'vancouver', b: 'santa-fe', points: 13 },
  { id: 'win-hou', a: 'winnipeg', b: 'houston', points: 12 },
  { id: 'win-lr', a: 'winnipeg', b: 'little-rock', points: 11 },
  { id: 'cal-nas', a: 'calgary', b: 'nashville', points: 14 },
  { id: 'chi-atl', a: 'chicago', b: 'atlanta', points: 5 },
  { id: 'chi-bos', a: 'chicago', b: 'boston', points: 7 },
  { id: 'chi-ny', a: 'chicago', b: 'new-york', points: 5 },
  { id: 'den-stl', a: 'denver', b: 'saint-louis', points: 6 },
  { id: 'dul-dal', a: 'duluth', b: 'dallas', points: 7 },
  { id: 'hou-was', a: 'houston', b: 'washington', points: 10 },
  { id: 'kc-bos', a: 'kansas-city', b: 'boston', points: 11 },
  { id: 'lv-mia', a: 'las-vegas', b: 'miami', points: 21 },
  { id: 'lv-ny', a: 'las-vegas', b: 'new-york', points: 19 },
  { id: 'la-atl', a: 'los-angeles', b: 'atlanta', points: 15 },
  { id: 'la-cal', a: 'los-angeles', b: 'calgary', points: 12 },
  { id: 'la-okc', a: 'los-angeles', b: 'oklahoma-city', points: 9 },
  { id: 'mtl-dal', a: 'montreal', b: 'dallas', points: 13 },
  { id: 'mtl-ral', a: 'montreal', b: 'raleigh', points: 7 },
  { id: 'nas-ny', a: 'nashville', b: 'new-york', points: 6 },
  { id: 'ny-mia', a: 'new-york', b: 'miami', points: 10 },
  { id: 'oma-no', a: 'omaha', b: 'new-orleans', points: 8 },
  { id: 'phx-bos', a: 'phoenix', b: 'boston', points: 19 },
  { id: 'pit-no', a: 'pittsburgh', b: 'new-orleans', points: 8 },
  { id: 'por-hou', a: 'portland', b: 'houston', points: 16 },
  { id: 'por-pit', a: 'portland', b: 'pittsburgh', points: 19 },
  { id: 'slc-chi', a: 'salt-lake-city', b: 'chicago', points: 11 },
  { id: 'slc-kc', a: 'salt-lake-city', b: 'kansas-city', points: 7 },
  { id: 'sf-sau', a: 'san-francisco', b: 'sault-ste-marie', points: 17 },
  { id: 'sf-was', a: 'san-francisco', b: 'washington', points: 21 },
  { id: 'sau-mia', a: 'sault-ste-marie', b: 'miami', points: 12 },
  { id: 'sea-lv', a: 'seattle', b: 'las-vegas', points: 10 },
  { id: 'sea-okc', a: 'seattle', b: 'oklahoma-city', points: 14 },
  { id: 'stl-mia', a: 'saint-louis', b: 'miami', points: 8 },
  { id: 'tor-cha', a: 'toronto', b: 'charleston', points: 6 },
  { id: 'van-den', a: 'vancouver', b: 'denver', points: 11 },
  { id: 'van-dul', a: 'vancouver', b: 'duluth', points: 13 },
  { id: 'was-atl', a: 'washington', b: 'atlanta', points: 4 },
  { id: 'win-sfe', a: 'winnipeg', b: 'santa-fe', points: 10 },
];

export const TTR_UNITED_STATES_MAP: TtrMapDefinition = {
  id: 'united-states',
  name: 'United States',
  minPlayers: 2,
  maxPlayers: 5,
  trainsPerPlayer: 45,
  stationsPerPlayer: 0,
  unplacedStationBonus: 0,
  routePoints: TTR_ROUTE_POINTS,
  deck: { cardsPerColor: 12, locomotives: 14 },
  setup: {
    trainCards: 4,
    longTicketThreshold: 17,
    initialLongTickets: 1,
    initialRegularTickets: 3,
    minInitialKeep: 3,
    longTicketsMandatory: true,
    ticketDraw: 3,
    minTicketKeep: 1,
  },
  rules: {
    doubleRouteLockMaxPlayers: 3,
    oneRoutePerGroupPerPlayer: true,
    faceUpCount: 5,
    faceUpLocomotiveReset: 3,
    endgameTrainThreshold: 2,
    longestPathBonus: 10,
    mandalaBonus: false,
    tiebreak: 'longest-path',
  },
  cities: CITIES,
  routes: ROUTES,
  destinationTickets: DESTINATION_TICKETS,
};
