import './avalon/index.js';
import './exploding-kittens/index.js';
import './sheriff/index.js';
import './splendor/index.js';
import './name-it/index.js';
import './insider/index.js';
import './hues-and-cues/index.js';
import './welcome-to-the-dungeon/index.js';
import './ticket-to-ride/index.js';
