/** CS Files — Cloudinary card decks + scene stubs (scene content TBD). */

export interface CsFilesCardDef {
  id: string;
  publicId: string;
  version: number;
  label: string;
}

export type CsFilesSceneKind = 'location' | 'causeOfDeath' | 'situation';

export interface CsFilesSceneTileDef {
  id: string;
  kind: CsFilesSceneKind;
  label: string;
  options: string[];
}

/** Prefer per-card version; shared batch pin for helpers. */
export const CS_FILES_CLOUD_VERSION = 'v1784634949';

export const CS_FILES_BLUE_CARDS: readonly CsFilesCardDef[] = [
  { id: 'alcohol_bpabqv', publicId: 'alcohol_bpabqv', version: 1784634903, label: 'alcohol' },
  { id: 'amoeba_yhvqqa', publicId: 'amoeba_yhvqqa', version: 1784634903, label: 'amoeba' },
  { id: 'arsenic_by7wms', publicId: 'arsenic_by7wms', version: 1784634916, label: 'arsenic' },
  { id: 'arson_e2onpd', publicId: 'arson_e2onpd', version: 1784634905, label: 'arson' },
  { id: 'axe_ha2syz', publicId: 'axe_ha2syz', version: 1784634906, label: 'axe' },
  {
    id: 'bamboo-tip_jypfcc',
    publicId: 'bamboo-tip_jypfcc',
    version: 1784634904,
    label: 'bamboo tip',
  },
  { id: 'bat_o6nfmr', publicId: 'bat_o6nfmr', version: 1784634910, label: 'bat' },
  { id: 'bees_k2tdz3', publicId: 'bees_k2tdz3', version: 1784634903, label: 'bees' },
  { id: 'belt_bzehlw', publicId: 'belt_bzehlw', version: 1784634907, label: 'belt' },
  {
    id: 'bite-and-tear_w2lpra',
    publicId: 'bite-and-tear_w2lpra',
    version: 1784634906,
    label: 'bite and tear',
  },
  {
    id: 'black-widow_bzgr0p',
    publicId: 'black-widow_bzgr0p',
    version: 1784634903,
    label: 'black widow',
  },
  { id: 'blender_anng33', publicId: 'blender_anng33', version: 1784634910, label: 'blender' },
  {
    id: 'blood-release_vfkraf',
    publicId: 'blood-release_vfkraf',
    version: 1784634911,
    label: 'blood release',
  },
  {
    id: 'blood-sample_yq7rmj',
    publicId: 'blood-sample_yq7rmj',
    version: 1784634903,
    label: 'blood sample',
  },
  {
    id: 'box-cutter_tobw7l',
    publicId: 'box-cutter_tobw7l',
    version: 1784634908,
    label: 'box cutter',
  },
  { id: 'brick_ikcada', publicId: 'brick_ikcada', version: 1784634904, label: 'brick' },
  { id: 'bury_gb0wme', publicId: 'bury_gb0wme', version: 1784634905, label: 'bury' },
  {
    id: 'candlestick_nzhrtq',
    publicId: 'candlestick_nzhrtq',
    version: 1784634907,
    label: 'candlestick',
  },
  { id: 'chainsaw_umnq5n', publicId: 'chainsaw_umnq5n', version: 1784634911, label: 'chainsaw' },
  { id: 'chemicals_augjtx', publicId: 'chemicals_augjtx', version: 1784634911, label: 'chemicals' },
  { id: 'cleaver_hhbz8d', publicId: 'cleaver_hhbz8d', version: 1784634905, label: 'cleaver' },
  { id: 'crutch_ayqjpa', publicId: 'crutch_ayqjpa', version: 1784634909, label: 'crutch' },
  { id: 'dagger_ibysnt', publicId: 'dagger_ibysnt', version: 1784634912, label: 'dagger' },
  { id: 'death-ray_by4ni2', publicId: 'death-ray_by4ni2', version: 1784634904, label: 'death ray' },
  {
    id: 'dirty-hands_yydoyh',
    publicId: 'dirty-hands_yydoyh',
    version: 1784634904,
    label: 'dirty hands',
  },
  {
    id: 'dirty-water_meesov',
    publicId: 'dirty-water_meesov',
    version: 1784634913,
    label: 'dirty water',
  },
  { id: 'dismember_ydpiya', publicId: 'dismember_ydpiya', version: 1784634914, label: 'dismember' },
  { id: 'drill_sn2xal', publicId: 'drill_sn2xal', version: 1784634905, label: 'drill' },
  { id: 'drown_iwp5my', publicId: 'drown_iwp5my', version: 1784634908, label: 'drown' },
  { id: 'dumbbell_geoquc', publicId: 'dumbbell_geoquc', version: 1784634908, label: 'dumbbell' },
  { id: 'e-bike_adnys1', publicId: 'e-bike_adnys1', version: 1784634906, label: 'e bike' },
  {
    id: 'electric-baton_w5fq6r',
    publicId: 'electric-baton_w5fq6r',
    version: 1784634909,
    label: 'electric baton',
  },
  {
    id: 'electric-current_huhmzo',
    publicId: 'electric-current_huhmzo',
    version: 1784634906,
    label: 'electric current',
  },
  {
    id: 'explosives_rd0x5b',
    publicId: 'explosives_rd0x5b',
    version: 1784634908,
    label: 'explosives',
  },
  {
    id: 'folding-chair_vbcu5g',
    publicId: 'folding-chair_vbcu5g',
    version: 1784634913,
    label: 'folding chair',
  },
  { id: 'gunpowder_tcv51c', publicId: 'gunpowder_tcv51c', version: 1784634919, label: 'gunpowder' },
  { id: 'hammer_ymw01o', publicId: 'hammer_ymw01o', version: 1784634923, label: 'hammer' },
  { id: 'hook_k9tjqz', publicId: 'hook_k9tjqz', version: 1784634910, label: 'hook' },
  {
    id: 'ice-skates_wjmmgk',
    publicId: 'ice-skates_wjmmgk',
    version: 1784634910,
    label: 'ice skates',
  },
  {
    id: 'illegal-drug_wx082f',
    publicId: 'illegal-drug_wx082f',
    version: 1784634919,
    label: 'illegal drug',
  },
  { id: 'injection_zoa2in', publicId: 'injection_zoa2in', version: 1784634920, label: 'injection' },
  { id: 'kerosene_web6g8', publicId: 'kerosene_web6g8', version: 1784634913, label: 'kerosene' },
  { id: 'kick_ydzp8s', publicId: 'kick_ydzp8s', version: 1784634910, label: 'kick' },
  {
    id: 'knife-and-fork_ladd6r',
    publicId: 'knife-and-fork_ladd6r',
    version: 1784634913,
    label: 'knife and fork',
  },
  {
    id: 'laser-shark_adfgru',
    publicId: 'laser-shark_adfgru',
    version: 1784634904,
    label: 'laser shark',
  },
  { id: 'lighter_gesimg', publicId: 'lighter_gesimg', version: 1784634942, label: 'lighter' },
  {
    id: 'liquid-drug_dpa4lv',
    publicId: 'liquid-drug_dpa4lv',
    version: 1784634914,
    label: 'liquid drug',
  },
  {
    id: 'locked-room_tn2kfg',
    publicId: 'locked-room_tn2kfg',
    version: 1784634908,
    label: 'locked room',
  },
  { id: 'machete_f09gm4', publicId: 'machete_f09gm4', version: 1784634915, label: 'machete' },
  { id: 'machine_vlqbyh', publicId: 'machine_vlqbyh', version: 1784634921, label: 'machine' },
  { id: 'mad-dog_dau2sh', publicId: 'mad-dog_dau2sh', version: 1784634909, label: 'mad dog' },
  { id: 'match_luqbba', publicId: 'match_luqbba', version: 1784634915, label: 'match' },
  { id: 'mercury_mrmjg9', publicId: 'mercury_mrmjg9', version: 1784634915, label: 'mercury' },
  {
    id: 'metal-chain_bxcp1n',
    publicId: 'metal-chain_bxcp1n',
    version: 1784634912,
    label: 'metal chain',
  },
  {
    id: 'metal-wire_hstagk',
    publicId: 'metal-wire_hstagk',
    version: 1784634912,
    label: 'metal wire',
  },
  { id: 'overdose_yaxfda', publicId: 'overdose_yaxfda', version: 1784634929, label: 'overdose' },
  {
    id: 'packing-tape_o55zjt',
    publicId: 'packing-tape_o55zjt',
    version: 1784634915,
    label: 'packing tape',
  },
  { id: 'pesticide_p8sgrs', publicId: 'pesticide_p8sgrs', version: 1784634912, label: 'pesticide' },
  { id: 'pill_k2f5q0', publicId: 'pill_k2f5q0', version: 1784634920, label: 'pill' },
  { id: 'pillow_eojfvl', publicId: 'pillow_eojfvl', version: 1784634910, label: 'pillow' },
  { id: 'pistol_mp9ana', publicId: 'pistol_mp9ana', version: 1784634912, label: 'pistol' },
  { id: 'plague_vhoo7a', publicId: 'plague_vhoo7a', version: 1784634917, label: 'plague' },
  {
    id: 'plastic-bag_rxqtwd',
    publicId: 'plastic-bag_rxqtwd',
    version: 1784634916,
    label: 'plastic bag',
  },
  {
    id: 'poisonous-gas_idfvlr',
    publicId: 'poisonous-gas_idfvlr',
    version: 1784634907,
    label: 'poisonous gas',
  },
  {
    id: 'poisonous-needle_whhsr3',
    publicId: 'poisonous-needle_whhsr3',
    version: 1784634913,
    label: 'poisonous needle',
  },
  {
    id: 'potted-plant_nlmuoz',
    publicId: 'potted-plant_nlmuoz',
    version: 1784634937,
    label: 'potted plant',
  },
  {
    id: 'powder-drug_xhcbwp',
    publicId: 'powder-drug_xhcbwp',
    version: 1784634917,
    label: 'powder drug',
  },
  { id: 'punch_yfyuxh', publicId: 'punch_yfyuxh', version: 1784634917, label: 'punch' },
  { id: 'push_xdkhyw', publicId: 'push_xdkhyw', version: 1784634913, label: 'push' },
  { id: 'radiation_glqndd', publicId: 'radiation_glqndd', version: 1784634969, label: 'radiation' },
  {
    id: 'razor-blade_r3f4ao',
    publicId: 'razor-blade_r3f4ao',
    version: 1784634970,
    label: 'razor blade',
  },
  { id: 'rope_ekzp8m', publicId: 'rope_ekzp8m', version: 1784634918, label: 'rope' },
  { id: 'scarf_ozhhrr', publicId: 'scarf_ozhhrr', version: 1784634914, label: 'scarf' },
  { id: 'scissors_adkyue', publicId: 'scissors_adkyue', version: 1784634969, label: 'scissors' },
  { id: 'sculpture_ttdh93', publicId: 'sculpture_ttdh93', version: 1784634969, label: 'sculpture' },
  { id: 'smoke_e0nbpg', publicId: 'smoke_e0nbpg', version: 1784634918, label: 'smoke' },
  { id: 'sniper_wfcupx', publicId: 'sniper_wfcupx', version: 1784634916, label: 'sniper' },
  {
    id: 'starvation_ki4ytk',
    publicId: 'starvation_ki4ytk',
    version: 1784634970,
    label: 'starvation',
  },
  {
    id: 'steel-tube_e4ng4f',
    publicId: 'steel-tube_e4ng4f',
    version: 1784634970,
    label: 'steel tube',
  },
  { id: 'stone_nl18fj', publicId: 'stone_nl18fj', version: 1784634917, label: 'stone' },
  {
    id: 'sulfuric-acid_kllsqh',
    publicId: 'sulfuric-acid_kllsqh',
    version: 1784634918,
    label: 'sulfuric acid',
  },
  { id: 'surgery_oow67l', publicId: 'surgery_oow67l', version: 1784634918, label: 'surgery' },
  {
    id: 'throat-slit_uuyxpn',
    publicId: 'throat-slit_uuyxpn',
    version: 1784634970,
    label: 'throat slit',
  },
  { id: 'towel_v8ggxa', publicId: 'towel_v8ggxa', version: 1784634919, label: 'towel' },
  { id: 'trample_f8sxmp', publicId: 'trample_f8sxmp', version: 1784634907, label: 'trample' },
  { id: 'trophy_a9oxcf', publicId: 'trophy_a9oxcf', version: 1784634920, label: 'trophy' },
  { id: 'trowel_bxnish', publicId: 'trowel_bxnish', version: 1784634921, label: 'trowel' },
  { id: 'unarmed_zwdobh', publicId: 'unarmed_zwdobh', version: 1784634922, label: 'unarmed' },
  {
    id: 'venomous-scorpion_vdtvl7',
    publicId: 'venomous-scorpion_vdtvl7',
    version: 1784634922,
    label: 'venomous scorpion',
  },
  {
    id: 'venomous-snake_h8ybnq',
    publicId: 'venomous-snake_h8ybnq',
    version: 1784634922,
    label: 'venomous snake',
  },
  {
    id: 'video-game-console_gbydic',
    publicId: 'video-game-console_gbydic',
    version: 1784634923,
    label: 'video game console',
  },
  { id: 'virus_ekfiet', publicId: 'virus_ekfiet', version: 1784634924, label: 'virus' },
  { id: 'whip_ypz2j7', publicId: 'whip_ypz2j7', version: 1784634924, label: 'whip' },
  { id: 'wine_cyqdlv', publicId: 'wine_cyqdlv', version: 1784634925, label: 'wine' },
  { id: 'wire_mceyxs', publicId: 'wire_mceyxs', version: 1784634925, label: 'wire' },
  { id: 'work_p1vix5', publicId: 'work_p1vix5', version: 1784634971, label: 'work' },
  { id: 'wrench_yl1qst', publicId: 'wrench_yl1qst', version: 1784634925, label: 'wrench' },
] as const;

export const CS_FILES_BROWN_CARDS: readonly CsFilesCardDef[] = [
  {
    id: 'air-conditioning_lajlmq',
    publicId: 'air-conditioning_lajlmq',
    version: 1784634919,
    label: 'air conditioning',
  },
  { id: 'antique_bu7tm8', publicId: 'antique_bu7tm8', version: 1784634932, label: 'antique' },
  { id: 'ants_ulnflz', publicId: 'ants_ulnflz', version: 1784634920, label: 'ants' },
  { id: 'apple_rjehvr', publicId: 'apple_rjehvr', version: 1784634939, label: 'apple' },
  {
    id: 'badge-with-lanyard_sojzlx',
    publicId: 'badge-with-lanyard_sojzlx',
    version: 1784634915,
    label: 'badge with lanyard',
  },
  { id: 'badge_ab6erw', publicId: 'badge_ab6erw', version: 1784634946, label: 'badge' },
  {
    id: 'bamboo-steamer_ev0ej3',
    publicId: 'bamboo-steamer_ev0ej3',
    version: 1784634916,
    label: 'bamboo steamer',
  },
  { id: 'bandage_aqfobt', publicId: 'bandage_aqfobt', version: 1784634946, label: 'bandage' },
  { id: 'banknote_cjlzju', publicId: 'banknote_cjlzju', version: 1784634922, label: 'banknote' },
  { id: 'bell_cg2kex', publicId: 'bell_cg2kex', version: 1784634947, label: 'bell' },
  {
    id: 'betting-chips_jbnufq',
    publicId: 'betting-chips_jbnufq',
    version: 1784634923,
    label: 'betting chips',
  },
  { id: 'blood_xc6fsx', publicId: 'blood_xc6fsx', version: 1784634947, label: 'blood' },
  { id: 'bone_ryynee', publicId: 'bone_ryynee', version: 1784634923, label: 'bone' },
  { id: 'book_gfjxgz', publicId: 'book_gfjxgz', version: 1784634947, label: 'book' },
  { id: 'bracelet_dgelw3', publicId: 'bracelet_dgelw3', version: 1784634923, label: 'bracelet' },
  { id: 'bread_oaww6k', publicId: 'bread_oaww6k', version: 1784634947, label: 'bread' },
  { id: 'briefs_jbkhww', publicId: 'briefs_jbkhww', version: 1784634948, label: 'briefs' },
  { id: 'broom_dijhyu', publicId: 'broom_dijhyu', version: 1784634948, label: 'broom' },
  { id: 'bullet_ww8ezn', publicId: 'bullet_ww8ezn', version: 1784634924, label: 'bullet' },
  { id: 'button_o2dsq0', publicId: 'button_o2dsq0', version: 1784634948, label: 'button' },
  { id: 'cake_vypvsv', publicId: 'cake_vypvsv', version: 1784634948, label: 'cake' },
  { id: 'calendar_fzi8ib', publicId: 'calendar_fzi8ib', version: 1784634948, label: 'calendar' },
  { id: 'candy_bneigx', publicId: 'candy_bneigx', version: 1784634949, label: 'candy' },
  { id: 'carton_ufjaiu', publicId: 'carton_ufjaiu', version: 1784634949, label: 'carton' },
  {
    id: 'cassette-tape_owtvmp',
    publicId: 'cassette-tape_owtvmp',
    version: 1784634949,
    label: 'cassette tape',
  },
  { id: 'cat_d3m3ss', publicId: 'cat_d3m3ss', version: 1784634925, label: 'cat' },
  {
    id: 'certificate_wsx3cy',
    publicId: 'certificate_wsx3cy',
    version: 1784634925,
    label: 'certificate',
  },
  { id: 'chalk_xtnj02', publicId: 'chalk_xtnj02', version: 1784634926, label: 'chalk' },
  { id: 'cigar_jfkjoe', publicId: 'cigar_jfkjoe', version: 1784634926, label: 'cigar' },
  {
    id: 'cigarette-ash_oxcopc',
    publicId: 'cigarette-ash_oxcopc',
    version: 1784634926,
    label: 'cigarette ash',
  },
  {
    id: 'cigarette-butt_k2ka5l',
    publicId: 'cigarette-butt_k2ka5l',
    version: 1784634949,
    label: 'cigarette butt',
  },
  {
    id: 'cleaning-cloth_izdwrr',
    publicId: 'cleaning-cloth_izdwrr',
    version: 1784634950,
    label: 'cleaning cloth',
  },
  { id: 'cockroach_ln1jli', publicId: 'cockroach_ln1jli', version: 1784634927, label: 'cockroach' },
  { id: 'coffee_jysmim', publicId: 'coffee_jysmim', version: 1784634950, label: 'coffee' },
  { id: 'coins_aqdxxi', publicId: 'coins_aqdxxi', version: 1784634927, label: 'coins' },
  { id: 'comics_bq54jp', publicId: 'comics_bq54jp', version: 1784634950, label: 'comics' },
  {
    id: 'computer-disk_wv7evk',
    publicId: 'computer-disk_wv7evk',
    version: 1784634950,
    label: 'computer disk',
  },
  {
    id: 'computer-mouse_jourzs',
    publicId: 'computer-mouse_jourzs',
    version: 1784634927,
    label: 'computer mouse',
  },
  { id: 'computer_urie4i', publicId: 'computer_urie4i', version: 1784634927, label: 'computer' },
  {
    id: 'confidential-letter_lojapa',
    publicId: 'confidential-letter_lojapa',
    version: 1784634951,
    label: 'confidential letter',
  },
  {
    id: 'cosmetic-mask_l4abds',
    publicId: 'cosmetic-mask_l4abds',
    version: 1784634927,
    label: 'cosmetic mask',
  },
  { id: 'cotton_f7z1wx', publicId: 'cotton_f7z1wx', version: 1784634951, label: 'cotton' },
  { id: 'cup_makv6q', publicId: 'cup_makv6q', version: 1784634928, label: 'cup' },
  { id: 'curtains_xlfdx4', publicId: 'curtains_xlfdx4', version: 1784634928, label: 'curtains' },
  { id: 'dentures_ulzut3', publicId: 'dentures_ulzut3', version: 1784634928, label: 'dentures' },
  { id: 'diamond_k4lvrb', publicId: 'diamond_k4lvrb', version: 1784634951, label: 'diamond' },
  { id: 'diary_pypc99', publicId: 'diary_pypc99', version: 1784634928, label: 'diary' },
  { id: 'dice_fyumbv', publicId: 'dice_fyumbv', version: 1784634953, label: 'dice' },
  {
    id: 'dictionary_kobdkx',
    publicId: 'dictionary_kobdkx',
    version: 1784634952,
    label: 'dictionary',
  },
  { id: 'dirt_ukkokr', publicId: 'dirt_ukkokr', version: 1784634952, label: 'dirt' },
  { id: 'documents_ugciay', publicId: 'documents_ugciay', version: 1784634928, label: 'documents' },
  { id: 'dog_fur_rlevqu', publicId: 'dog_fur_rlevqu', version: 1784634971, label: 'dog fur' },
  { id: 'dust_r075uk', publicId: 'dust_r075uk', version: 1784634952, label: 'dust' },
  { id: 'earrings_puytyp', publicId: 'earrings_puytyp', version: 1784634929, label: 'earrings' },
  { id: 'eggs_o9uicc', publicId: 'eggs_o9uicc', version: 1784634929, label: 'eggs' },
  {
    id: 'electric-circuit_cpl72l',
    publicId: 'electric-circuit_cpl72l',
    version: 1784634952,
    label: 'electric circuit',
  },
  { id: 'envelope_ixildd', publicId: 'envelope_ixildd', version: 1784634953, label: 'envelope' },
  {
    id: 'exam-paper_z0b4dy',
    publicId: 'exam-paper_z0b4dy',
    version: 1784634929,
    label: 'exam paper',
  },
  {
    id: 'express-courier_daxtm9',
    publicId: 'express-courier_daxtm9',
    version: 1784634953,
    label: 'express courier',
  },
  { id: 'fan_s8wepk', publicId: 'fan_s8wepk', version: 1784634953, label: 'fan' },
  { id: 'fax_z9nt6z', publicId: 'fax_z9nt6z', version: 1784634953, label: 'fax' },
  {
    id: 'fiber-optics_ocjesj',
    publicId: 'fiber-optics_ocjesj',
    version: 1784634953,
    label: 'fiber optics',
  },
  {
    id: 'fingernails_h03umq',
    publicId: 'fingernails_h03umq',
    version: 1784634930,
    label: 'fingernails',
  },
  {
    id: 'flash-light_ymbc2e',
    publicId: 'flash-light_ymbc2e',
    version: 1784634930,
    label: 'flash light',
  },
  { id: 'flip-flop_jucrdu', publicId: 'flip-flop_jucrdu', version: 1784634930, label: 'flip flop' },
  { id: 'flute_ynmegl', publicId: 'flute_ynmegl', version: 1784634954, label: 'flute' },
  { id: 'flyer_gdlros', publicId: 'flyer_gdlros', version: 1784634954, label: 'flyer' },
  {
    id: 'food-ingredients_ljhg6j',
    publicId: 'food-ingredients_ljhg6j',
    version: 1784634954,
    label: 'food ingredients',
  },
  { id: 'gear_x2raqt', publicId: 'gear_x2raqt', version: 1784634930, label: 'gear' },
  { id: 'gift_tae4wj', publicId: 'gift_tae4wj', version: 1784634931, label: 'gift' },
  { id: 'gloves_lxsrwe', publicId: 'gloves_lxsrwe', version: 1784634931, label: 'gloves' },
  { id: 'glue_vt7yju', publicId: 'glue_vt7yju', version: 1784634931, label: 'glue' },
  { id: 'graffiti_sjhfvw', publicId: 'graffiti_sjhfvw', version: 1784634954, label: 'graffiti' },
  { id: 'hair_lmozfo', publicId: 'hair_lmozfo', version: 1784634931, label: 'hair' },
  { id: 'hairpin_ysxpsj', publicId: 'hairpin_ysxpsj', version: 1784634931, label: 'hairpin' },
  { id: 'handcuffs_njgvni', publicId: 'handcuffs_njgvni', version: 1784634955, label: 'handcuffs' },
  { id: 'hanger_xg1lgb', publicId: 'hanger_xg1lgb', version: 1784634955, label: 'hanger' },
  { id: 'hat_gc5xrz', publicId: 'hat_gc5xrz', version: 1784634955, label: 'hat' },
  { id: 'headset_qs2eyq', publicId: 'headset_qs2eyq', version: 1784634932, label: 'headset' },
  { id: 'helmet_he5ej2', publicId: 'helmet_he5ej2', version: 1784634932, label: 'helmet' },
  {
    id: 'herbal-medicine_to4wwd',
    publicId: 'herbal-medicine_to4wwd',
    version: 1784634971,
    label: 'herbal medicine',
  },
  { id: 'high-heel_ugnryo', publicId: 'high-heel_ugnryo', version: 1784634932, label: 'high heel' },
  { id: 'hourglass_iqnamy', publicId: 'hourglass_iqnamy', version: 1784634933, label: 'hourglass' },
  { id: 'ice_owk2pc', publicId: 'ice_owk2pc', version: 1784634955, label: 'ice' },
  { id: 'id-card_mnluzz', publicId: 'id-card_mnluzz', version: 1784634956, label: 'id card' },
  { id: 'ink_bog3fx', publicId: 'ink_bog3fx', version: 1784634933, label: 'ink' },
  { id: 'insect_dsqbk3', publicId: 'insect_dsqbk3', version: 1784634933, label: 'insect' },
  {
    id: 'instant-noodles_njwcrv',
    publicId: 'instant-noodles_njwcrv',
    version: 1784634919,
    label: 'instant noodles',
  },
  {
    id: 'internet-cable_coal4z',
    publicId: 'internet-cable_coal4z',
    version: 1784634956,
    label: 'internet cable',
  },
  {
    id: 'invitation-card_xebmug',
    publicId: 'invitation-card_xebmug',
    version: 1784634933,
    label: 'invitation card',
  },
  { id: 'iou-note_t9ppth', publicId: 'iou-note_t9ppth', version: 1784634956, label: 'iou note' },
  { id: 'iron_gveqst', publicId: 'iron_gveqst', version: 1784634933, label: 'iron' },
  { id: 'iv-bag_pgwnws', publicId: 'iv-bag_pgwnws', version: 1784634956, label: 'iv bag' },
  { id: 'jacket_btwack', publicId: 'jacket_btwack', version: 1784634934, label: 'jacket' },
  { id: 'jewelry_u6s7ek', publicId: 'jewelry_u6s7ek', version: 1784634972, label: 'jewelry' },
  { id: 'juice_zndq09', publicId: 'juice_zndq09', version: 1784634934, label: 'juice' },
  { id: 'key_uav37r', publicId: 'key_uav37r', version: 1784634934, label: 'key' },
  { id: 'leaf_dsqxbu', publicId: 'leaf_dsqxbu', version: 1784634956, label: 'leaf' },
  {
    id: 'leather-bag_atcak1',
    publicId: 'leather-bag_atcak1',
    version: 1784634957,
    label: 'leather bag',
  },
  {
    id: 'leather-shoe_owv8ta',
    publicId: 'leather-shoe_owv8ta',
    version: 1784634957,
    label: 'leather shoe',
  },
  { id: 'lens_kncecd', publicId: 'lens_kncecd', version: 1784634957, label: 'lens' },
  {
    id: 'light-bulb_r826ks',
    publicId: 'light-bulb_r826ks',
    version: 1784634934,
    label: 'light bulb',
  },
  { id: 'lipstick_qo7u79', publicId: 'lipstick_qo7u79', version: 1784634935, label: 'lipstick' },
  { id: 'lock_dsw0td', publicId: 'lock_dsw0td', version: 1784634935, label: 'lock' },
  {
    id: 'lottery-ticket_daj4nv',
    publicId: 'lottery-ticket_daj4nv',
    version: 1784634935,
    label: 'lottery ticket',
  },
  {
    id: 'love-letter_dhwjiu',
    publicId: 'love-letter_dhwjiu',
    version: 1784634957,
    label: 'love letter',
  },
  { id: 'luggage_ktbsri', publicId: 'luggage_ktbsri', version: 1784634935, label: 'luggage' },
  { id: 'lunch-box_lpcjva', publicId: 'lunch-box_lpcjva', version: 1784634936, label: 'lunch box' },
  { id: 'magazine_uz12v0', publicId: 'magazine_uz12v0', version: 1784634936, label: 'magazine' },
  {
    id: 'mahjong-tiles_cjzqke',
    publicId: 'mahjong-tiles_cjzqke',
    version: 1784634958,
    label: 'mahjong tiles',
  },
  { id: 'map_tfzovt', publicId: 'map_tfzovt', version: 1784634958, label: 'map' },
  { id: 'mark_nb6keh', publicId: 'mark_nb6keh', version: 1784634936, label: 'mark' },
  { id: 'mask_oypglq', publicId: 'mask_oypglq', version: 1784634958, label: 'mask' },
  { id: 'maze_a9d6pv', publicId: 'maze_a9d6pv', version: 1784634936, label: 'maze' },
  { id: 'menu_ayb2gp', publicId: 'menu_ayb2gp', version: 1784634958, label: 'menu' },
  { id: 'mirror_jhm9fd', publicId: 'mirror_jhm9fd', version: 1784634971, label: 'mirror' },
  {
    id: 'mobile-phone_bolvce',
    publicId: 'mobile-phone_bolvce',
    version: 1784634936,
    label: 'mobile phone',
  },
  { id: 'model_flgxxb', publicId: 'model_flgxxb', version: 1784634958, label: 'model' },
  {
    id: 'mosquito-coil_ioq0e8',
    publicId: 'mosquito-coil_ioq0e8',
    version: 1784634959,
    label: 'mosquito coil',
  },
  { id: 'mosquito_ia5pni', publicId: 'mosquito_ia5pni', version: 1784634959, label: 'mosquito' },
  { id: 'nail_dqhuib', publicId: 'nail_dqhuib', version: 1784634959, label: 'nail' },
  { id: 'name-card_bwzmpt', publicId: 'name-card_bwzmpt', version: 1784634959, label: 'name card' },
  { id: 'necklace_qqdfk8', publicId: 'necklace_qqdfk8', version: 1784634937, label: 'necklace' },
  {
    id: 'needle-and-thread_lhaer6',
    publicId: 'needle-and-thread_lhaer6',
    version: 1784634937,
    label: 'needle and thread',
  },
  { id: 'newspaper_aktybu', publicId: 'newspaper_aktybu', version: 1784634960, label: 'newspaper' },
  { id: 'note_p6gsqs', publicId: 'note_p6gsqs', version: 1784634937, label: 'note' },
  { id: 'notebook_fnbmic', publicId: 'notebook_fnbmic', version: 1784634938, label: 'notebook' },
  { id: 'numbers_s9yktk', publicId: 'numbers_s9yktk', version: 1784634960, label: 'numbers' },
  {
    id: 'office-supplies_tba76n',
    publicId: 'office-supplies_tba76n',
    version: 1784634938,
    label: 'office supplies',
  },
  {
    id: 'oil-painting_ihzydk',
    publicId: 'oil-painting_ihzydk',
    version: 1784634938,
    label: 'oil painting',
  },
  { id: 'oil-stain_uaktin', publicId: 'oil-stain_uaktin', version: 1784634938, label: 'oil stain' },
  { id: 'paint_x7exnb', publicId: 'paint_x7exnb', version: 1784634960, label: 'paint' },
  { id: 'panties_mjhfmg', publicId: 'panties_mjhfmg', version: 1784634939, label: 'panties' },
  { id: 'peanut_pp99wt', publicId: 'peanut_pp99wt', version: 1784634961, label: 'peanut' },
  { id: 'pen_q6txp4', publicId: 'pen_q6txp4', version: 1784634920, label: 'pen' },
  { id: 'perfume_v201qx', publicId: 'perfume_v201qx', version: 1784634961, label: 'perfume' },
  {
    id: 'photograph_kpiiiu',
    publicId: 'photograph_kpiiiu',
    version: 1784634961,
    label: 'photograph',
  },
  { id: 'plant_ciiaah', publicId: 'plant_ciiaah', version: 1784634961, label: 'plant' },
  { id: 'plastic_q4pwqm', publicId: 'plastic_q4pwqm', version: 1784634961, label: 'plastic' },
  {
    id: 'playing-cards_byg1xy',
    publicId: 'playing-cards_byg1xy',
    version: 1784634939,
    label: 'playing cards',
  },
  {
    id: 'pocket-watch_eejoz0',
    publicId: 'pocket-watch_eejoz0',
    version: 1784634939,
    label: 'pocket watch',
  },
  {
    id: 'postal-stamp_j6zuvh',
    publicId: 'postal-stamp_j6zuvh',
    version: 1784634939,
    label: 'postal stamp',
  },
  { id: 'powder_ibcnzz', publicId: 'powder_ibcnzz', version: 1784634940, label: 'powder' },
  {
    id: 'prescription_pivg9k',
    publicId: 'prescription_pivg9k',
    version: 1784634940,
    label: 'prescription',
  },
  { id: 'puppet_xz2vp3', publicId: 'puppet_xz2vp3', version: 1784634940, label: 'puppet' },
  { id: 'push-pin_gnc4lt', publicId: 'push-pin_gnc4lt', version: 1784634940, label: 'push pin' },
  { id: 'puzzle_pceb9c', publicId: 'puzzle_pceb9c', version: 1784634940, label: 'puzzle' },
  { id: 'quill_vtmulk', publicId: 'quill_vtmulk', version: 1784634921, label: 'quill' },
  { id: 'raincoat_kli4co', publicId: 'raincoat_kli4co', version: 1784634962, label: 'raincoat' },
  { id: 'rat_awm65b', publicId: 'rat_awm65b', version: 1784634962, label: 'rat' },
  { id: 'receipt_hf3ymq', publicId: 'receipt_hf3ymq', version: 1784634941, label: 'receipt' },
  { id: 'red-wine_ur0ohw', publicId: 'red-wine_ur0ohw', version: 1784634941, label: 'red wine' },
  { id: 'riddle_e1qz99', publicId: 'riddle_e1qz99', version: 1784634941, label: 'riddle' },
  { id: 'ring_mr4dmn', publicId: 'ring_mr4dmn', version: 1784634941, label: 'ring' },
  { id: 'rose_g3whyq', publicId: 'rose_g3whyq', version: 1784634972, label: 'rose' },
  {
    id: 'rubber-stamp_glkdlf',
    publicId: 'rubber-stamp_glkdlf',
    version: 1784634962,
    label: 'rubber stamp',
  },
  { id: 'sack_nouddo', publicId: 'sack_nouddo', version: 1784634962, label: 'sack' },
  {
    id: 'safety-pin_ds97jj',
    publicId: 'safety-pin_ds97jj',
    version: 1784634942,
    label: 'safety pin',
  },
  { id: 'sand_hnaqmx', publicId: 'sand_hnaqmx', version: 1784634942, label: 'sand' },
  { id: 'sawdust_r500y8', publicId: 'sawdust_r500y8', version: 1784634942, label: 'sawdust' },
  { id: 'seasoning_mdx04g', publicId: 'seasoning_mdx04g', version: 1784634971, label: 'seasoning' },
  { id: 'signature_sqbwyw', publicId: 'signature_sqbwyw', version: 1784634943, label: 'signature' },
  { id: 'skull_x7um30', publicId: 'skull_x7um30', version: 1784634943, label: 'skull' },
  { id: 'snacks_mqfzjm', publicId: 'snacks_mqfzjm', version: 1784634943, label: 'snacks' },
  { id: 'soap_ljhell', publicId: 'soap_ljhell', version: 1784634962, label: 'soap' },
  { id: 'sock_uzvs9t', publicId: 'sock_uzvs9t', version: 1784634963, label: 'sock' },
  {
    id: 'soft-drink_zghjqq',
    publicId: 'soft-drink_zghjqq',
    version: 1784634963,
    label: 'soft drink',
  },
  { id: 'speaker_uryvmh', publicId: 'speaker_uryvmh', version: 1784634963, label: 'speaker' },
  { id: 'specimen_yhjrel', publicId: 'specimen_yhjrel', version: 1784634943, label: 'specimen' },
  { id: 'spider_nnw5mj', publicId: 'spider_nnw5mj', version: 1784634964, label: 'spider' },
  {
    id: 'spinning-top_oaviqe',
    publicId: 'spinning-top_oaviqe',
    version: 1784634964,
    label: 'spinning top',
  },
  { id: 'sponge_nxllsq', publicId: 'sponge_nxllsq', version: 1784634943, label: 'sponge' },
  { id: 'spring_kz7zxw', publicId: 'spring_kz7zxw', version: 1784634964, label: 'spring' },
  {
    id: 'steamed-buns_vfqy66',
    publicId: 'steamed-buns_vfqy66',
    version: 1784634964,
    label: 'steamed buns',
  },
  { id: 'stockings_jtffzl', publicId: 'stockings_jtffzl', version: 1784634964, label: 'stockings' },
  {
    id: 'stuffed-toy_jrh8pd',
    publicId: 'stuffed-toy_jrh8pd',
    version: 1784634944,
    label: 'stuffed toy',
  },
  { id: 'suit_lqupo9', publicId: 'suit_lqupo9', version: 1784634965, label: 'suit' },
  {
    id: 'sunglasses_zrlanf',
    publicId: 'sunglasses_zrlanf',
    version: 1784634965,
    label: 'sunglasses',
  },
  {
    id: 'surgical-mask_c2cg6b',
    publicId: 'surgical-mask_c2cg6b',
    version: 1784634965,
    label: 'surgical mask',
  },
  {
    id: 'surveillance-camera_xfgj68',
    publicId: 'surveillance-camera_xfgj68',
    version: 1784634965,
    label: 'surveillance camera',
  },
  { id: 'switch_dxc9kw', publicId: 'switch_dxc9kw', version: 1784634966, label: 'switch' },
  { id: 'syringe_cgtgfl', publicId: 'syringe_cgtgfl', version: 1784634944, label: 'syringe' },
  {
    id: 'table-lamp_lqgtgj',
    publicId: 'table-lamp_lqgtgj',
    version: 1784634966,
    label: 'table lamp',
  },
  { id: 'take-out_bwl8ul', publicId: 'take-out_bwl8ul', version: 1784634966, label: 'take out' },
  { id: 'tattoo_rzfhmb', publicId: 'tattoo_rzfhmb', version: 1784634966, label: 'tattoo' },
  {
    id: 'tea-leaves_j9izqb',
    publicId: 'tea-leaves_j9izqb',
    version: 1784634944,
    label: 'tea leaves',
  },
  { id: 'telephone_bbxf51', publicId: 'telephone_bbxf51', version: 1784634944, label: 'telephone' },
  { id: 'test-tube_q4sfjf', publicId: 'test-tube_q4sfjf', version: 1784634967, label: 'test tube' },
  { id: 'tie_upymp6', publicId: 'tie_upymp6', version: 1784634967, label: 'tie' },
  { id: 'timber_xno3ln', publicId: 'timber_xno3ln', version: 1784634967, label: 'timber' },
  { id: 'tissue_o9z8db', publicId: 'tissue_o9z8db', version: 1784634967, label: 'tissue' },
  { id: 'tool-box_j6jxgp', publicId: 'tool-box_j6jxgp', version: 1784634945, label: 'tool box' },
  {
    id: 'toothpicks_uxaf89',
    publicId: 'toothpicks_uxaf89',
    version: 1784634968,
    label: 'toothpicks',
  },
  {
    id: 'toy-blocks_xcvnzh',
    publicId: 'toy-blocks_xcvnzh',
    version: 1784634967,
    label: 'toy blocks',
  },
  { id: 'toy_wvghfj', publicId: 'toy_wvghfj', version: 1784634972, label: 'toy' },
  { id: 'tweezers_vhc8vg', publicId: 'tweezers_vhc8vg', version: 1784634968, label: 'tweezers' },
  { id: 'umbrella_mqo8ow', publicId: 'umbrella_mqo8ow', version: 1784634945, label: 'umbrella' },
  { id: 'uniform_gcbl6t', publicId: 'uniform_gcbl6t', version: 1784634945, label: 'uniform' },
  {
    id: 'usb-flash-drive_ithofg',
    publicId: 'usb-flash-drive_ithofg',
    version: 1784634945,
    label: 'usb flash drive',
  },
  {
    id: 'vegetables_ulgna0',
    publicId: 'vegetables_ulgna0',
    version: 1784634946,
    label: 'vegetables',
  },
  {
    id: 'video-camera_rz1sqt',
    publicId: 'video-camera_rz1sqt',
    version: 1784634946,
    label: 'video camera',
  },
  { id: 'violin_oq2kpg', publicId: 'violin_oq2kpg', version: 1784634968, label: 'violin' },
  { id: 'wallet_cnt9xc', publicId: 'wallet_cnt9xc', version: 1784634946, label: 'wallet' },
  { id: 'watch_a8lvzq', publicId: 'watch_a8lvzq', version: 1784634968, label: 'watch' },
  { id: 'wig_cmjbpu', publicId: 'wig_cmjbpu', version: 1784634969, label: 'wig' },
] as const;

export const CS_FILES_LOCATION_CARDS: readonly CsFilesSceneTileDef[] = [
  {
    id: 'loc-1',
    kind: 'location',
    label: 'สถานที่เกิดเหตุ',
    options: [
      'ผับ / บาร์',
      'ร้านหนังสือ',
      'ร้านอาหาร',
      'โรงแรม',
      'โรงพยาบาล',
      'เขตก่อสร้าง / ไซต์งาน',
    ],
  },
  {
    id: 'loc-2',
    kind: 'location',
    label: 'สถานที่เกิดเหตุ',
    options: [
      'บ้านพักตากอากาศ',
      'สวนสาธารณะ',
      'ซูเปอร์มาร์เก็ต',
      'โรงเรียน',
      'ป่า / พงหญ้า',
      'ธนาคาร',
    ],
  },
  {
    id: 'loc-3',
    kind: 'location',
    label: 'สถานที่เกิดเหตุ',
    options: [
      'สนามเด็กเล่น / สนามกีฬา',
      'ห้องเรียน',
      'หอพัก',
      'โรงอาหาร',
      'ลิฟต์',
      'ห้องสุขา / ห้องน้ำ',
    ],
  },
  {
    id: 'loc-4',
    kind: 'location',
    label: 'สถานที่เกิดเหตุ',
    options: [
      'ห้องนั่งเล่น',
      'ห้องนอน',
      'ห้องเก็บของ',
      'ห้องอาบน้ำ / ห้องน้ำ',
      'ห้องครัว',
      'ระเบียง',
    ],
  },
] as const;

/** @deprecated ใช้ CS_FILES_LOCATION_CARDS */
export const CS_FILES_LOCATION_STUBS = CS_FILES_LOCATION_CARDS;

/** สาเหตุการตาย — ใบเดียว */
export const CS_FILES_CAUSE_OF_DEATH_CARD: CsFilesSceneTileDef = {
  id: 'cause-1',
  kind: 'causeOfDeath',
  label: 'สาเหตุการตาย',
  options: [
    'ขาดอากาศหายใจ / จมน้ำ',
    'บาดเจ็บสาหัส',
    'เสียเลือดมาก',
    'เจ็บป่วย / โรคประจำตัวกำเริบ',
    'ถูกยาพิษ / ได้รับสารพิษ',
    'อุบัติเหตุ',
  ],
};

export const CS_FILES_CAUSE_STUBS: readonly CsFilesSceneTileDef[] = [CS_FILES_CAUSE_OF_DEATH_CARD];

/** แผ่นสถานการณ์ — สุ่ม 4 จากสำรับนี้ในรอบแรก แล้วแทนที่ทีละใบในรอบ 2–3 */
export const CS_FILES_SITUATION_CARDS: readonly CsFilesSceneTileDef[] = [
  {
    id: 'sit-in-progress',
    kind: 'situation',
    label: 'กิจกรรมที่กำลังทำอยู่',
    options: [
      'ความบันเทิง / รื่นเริง',
      'พักผ่อนหย่อนใจ',
      'การชุมนุม / รวมตัวกัน',
      'การค้าขาย / เจรจาธุรกิจ',
      'การเยี่ยมเยียน',
      'รับประทานอาหาร / ร่วมโต๊ะอาหาร',
    ],
  },
  {
    id: 'sit-victims-clothes',
    kind: 'situation',
    label: 'การแต่งกายของเหยื่อ',
    options: [
      'เรียบร้อย / สะอาดตา',
      'ยุ่งเหยิง / หลุดลุ่ย',
      'หรูหรา / ดูดี',
      'ซอมซ่อ / มอมแมม',
      'แปลกประหลาด / พิสดาร',
      'เปลือยกาย / ไม่สวมเสื้อผ้า',
    ],
  },
  {
    id: 'sit-hint-on-corpse',
    kind: 'situation',
    label: 'ร่องรอยบนศพ',
    options: ['ศีรษะ', 'หน้าอก', 'มือ', 'ขา', 'เฉพาะจุด / บางส่วนของร่างกาย', 'ทั่วทั้งร่างกาย'],
  },
  {
    id: 'sit-weather',
    kind: 'situation',
    label: 'สภาพอากาศ',
    options: [
      'แดดจัด / แจ่มใส',
      'พายุฝนฟ้าคะนอง',
      'แห้งแล้ง',
      'ชื้นแฉะ / อับชื้น',
      'หนาวเย็น',
      'ร้อนจัด',
    ],
  },
  {
    id: 'sit-victims-identity',
    kind: 'situation',
    label: 'อัตลักษณ์ของเหยื่อ',
    options: [
      'เด็ก',
      'วัยรุ่น / วัยหนุ่มสาว',
      'วัยกลางคน',
      'ผู้สูงอายุ / คนชรา',
      'เพศชาย',
      'เพศหญิง',
    ],
  },
  {
    id: 'sit-time-of-death',
    kind: 'situation',
    label: 'เวลาที่เสียชีวิต',
    options: [
      'รุ่งอรุณ / เช้าตรู่',
      'ช่วงเช้า',
      'เที่ยงวัน',
      'ช่วงบ่าย',
      'ช่วงเย็น / ค่ำ',
      'ดึก / กลางคืน',
    ],
  },
  {
    id: 'sit-corpse-condition',
    kind: 'situation',
    label: 'สภาพศพ',
    options: [
      'ตัวยังอุ่นอยู่',
      'ศพเกร็ง / แข็งตัว',
      'เน่าเปื่อย',
      'ศพไม่สมบูรณ์ / ชิ้นส่วนสูญหาย',
      'ศพสมบูรณ์ดี',
      'บิดเบี้ยวผิดรูป',
    ],
  },
  {
    id: 'sit-murderers-personality',
    kind: 'situation',
    label: 'บุคลิกของผู้ร้าย',
    options: [
      'เย่อหยิ่ง / โอหัง',
      'ชั่วช้า / น่ารังเกียจ',
      'ดุร้าย / โกรธจัด',
      'โลภมาก',
      'ดุดัน / ก้าวร้าว',
      'วิตถาร / จิตไม่ปกติ',
    ],
  },
  {
    id: 'sit-duration-of-crime',
    kind: 'situation',
    label: 'ระยะเวลาในการก่อเหตุ',
    options: [
      'ชั่วครู่ / เกิดขึ้นทันที',
      'สั้นๆ / ใช้เวลาไม่นาน',
      'ค่อยเป็นค่อยไป',
      'ยืดเยื้อ / นาน',
      'นานหลายวัน',
      'ไม่ชัดเจน',
    ],
  },
  {
    id: 'sit-victims-occupation',
    kind: 'situation',
    label: 'อาชีพของเหยื่อ',
    options: [
      'เจ้าของกิจการ / นายจ้าง',
      'ผู้เชี่ยวชาญ / วิชาชีพเฉพาะ',
      'คนงาน / พนักงาน',
      'นักเรียน / นักศึกษา',
      'คนว่างงาน',
      'คนเกษียณอายุ',
    ],
  },
  {
    id: 'sit-state-of-scene',
    kind: 'situation',
    label: 'สภาพสถานที่เกิดเหตุ',
    options: [
      'มีเศษขยะ / ชิ้นส่วนกระจัดกระจาย',
      'มีเถ้าถ่าน',
      'มีรอยคราบน้ำ',
      'มีรอยแตกร้าว / ชำรุด',
      'รก / รกเกะกะ',
      'สะอาด / เรียบร้อย',
    ],
  },
  {
    id: 'sit-trace-at-scene',
    kind: 'situation',
    label: 'ร่องรอยในสถานที่เกิดเหตุ',
    options: [
      'รอยนิ้วมือ',
      'รอยเท้า',
      'รอยถลอก / รอยบวมช้ำ',
      'รอยคราบเลือด',
      'คราบสารคัดหลั่ง',
      'รอยแผลเป็น',
    ],
  },
  {
    id: 'sit-victims-build',
    kind: 'situation',
    label: 'รูปร่างของเหยื่อ',
    options: [
      'อ้วน / ตัวใหญ่',
      'ผอมแห้ง',
      'สูงใหญ่',
      'เตี้ย / ตัวเล็ก',
      'พิการ / รูปร่างผิดปกติ',
      'แข็งแรง / หุ่นดี',
    ],
  },
  {
    id: 'sit-sudden-incident',
    kind: 'situation',
    label: 'เหตุการณ์อุบัติขึ้นฉับพลัน',
    options: [
      'ไฟฟ้าดับ',
      'เกิดเพลิงไหม้',
      'เกิดการทะเลาะวิวาท',
      'ของมีค่าสูญหาย',
      'เสียงกรีดร้อง',
      'ไม่มีอะไรเกิดขึ้น',
    ],
  },
  {
    id: 'sit-day-of-crime',
    kind: 'situation',
    label: 'วันที่เกิดเหตุ',
    options: [
      'วันธรรมดา (จันทร์-ศุกร์)',
      'วันหยุดสุดสัปดาห์ (เสาร์-อาทิตย์)',
      'ฤดูใบไม้ผลิ',
      'ฤดูร้อน',
      'ฤดูใบไม้ร่วง',
      'ฤดูหนาว',
    ],
  },
  {
    id: 'sit-motive-of-crime',
    kind: 'situation',
    label: 'มูลเหตุจูงใจในการก่อเหตุ',
    options: [
      'ความแค้น / ความเกลียดชัง',
      'อำนาจ',
      'เงินทอง / ผลประโยชน์',
      'เรื่องความรัก / ตัณหา',
      'ความริษยา / หึงหวง',
      'ทวงคืนความยุติธรรม',
    ],
  },
  {
    id: 'sit-social-relationship',
    kind: 'situation',
    label: 'ความสัมพันธ์ทางสังคม',
    options: [
      'ญาติพี่น้อง',
      'เพื่อนฝูง',
      'เพื่อนร่วมงาน',
      'นายจ้าง / ลูกจ้าง',
      'คนรัก / คู่รัก',
      'คนแปลกหน้า',
    ],
  },
  {
    id: 'sit-general-impression',
    kind: 'situation',
    label: 'ภาพรวมของคดี',
    options: [
      'ธรรมดา / ทั่วๆ ไป',
      'แปลกใหม่ / มีความคิดสร้างสรรค์',
      'มีเงื่อนงำ / น่าสงสัย',
      'โหดเหี้ยม / โหดร้าย',
      'สยดสยอง',
      'ลึกลับ / ซ่อนเงื่อน',
    ],
  },
  {
    id: 'sit-noticed-by-bystander',
    kind: 'situation',
    label: 'สิ่งที่คนรอบข้างสังเกตเห็น',
    options: [
      'เสียงดังขึ้นทันที',
      'เสียงดังต่อเนื่องยาวนาน',
      'ได้กลิ่น',
      'มองเห็นเหตุการณ์',
      'เห็นการเคลื่อนไหว / ความคึกคัก',
      'ไม่พบสิ่งผิดปกติ',
    ],
  },
  {
    id: 'sit-evidence-left-behind',
    kind: 'situation',
    label: 'หลักฐานที่ทิ้งไว้',
    options: [
      'สิ่งของจากธรรมชาติ',
      'งานศิลปะ / ของสวยงาม',
      'ข้อความ / ตัวหนังสือ',
      'สิ่งของสังเคราะห์ / สิ่งที่มนุษย์สร้าง',
      'ของใช้ส่วนตัว',
      'สิ่งของที่ไม่เกี่ยวข้องกัน',
    ],
  },
  {
    id: 'sit-victims-expression',
    kind: 'situation',
    label: 'สีหน้าของเหยื่อ',
    options: [
      'สงบ / สงบนิ่ง',
      'ดิ้นรน / ขัดขืน',
      'หวาดกลัว',
      'เจ็บปวดทรมาน',
      'เรียบเฉย / ไม่แสดงความรู้สึก',
      'โกรธแค้น',
    ],
  },
] as const;

/** @deprecated ใช้ CS_FILES_SITUATION_CARDS */
export const CS_FILES_SITUATION_STUBS = CS_FILES_SITUATION_CARDS;

export function csFilesCardImagePath(card: Pick<CsFilesCardDef, 'publicId' | 'version'>): string {
  return `v${card.version}/${card.publicId}`;
}
